"""Run results and V1-shaped output rows.

A ``RunResult`` holds one buffer entry per *selected port*. A plain workflow
output selects one port under its own name; a wildcard ``$steps.x.*`` selects
every output of ``x`` as ``<name>/<output>``, so ports with different layouts
keep their own layout and metadata.

Rows follow V1's output construction::

    no grouped port                 [ {name: value, ...} ]
    top axis of a workflow input    one row per index of that axis
    top axis generated by a step    whole nested list copied into every row
    scalar port                     same value in every row
    nested positions                lists placed by index; a filtered or
                                    missing leaf is None, a filtered group []
    wildcard                        {output: value} at the ports' common
                                    axes; deeper axes stay nested lists

Values pass through ``Kind.to_output`` (with the declaration's options) and,
when serializing, ``Kind.to_serialized``. For a union of kinds, the first kind
whose hook succeeds wins, as in V1. After all hooks fail, a hook-free kind
only permits pass-through when its validator accepts the payload.
"""

from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Set, Tuple

from roboflow_workflows.execution_engine.v2.data import (
    Batch,
    EntryLayout,
    Index,
    WorkflowsBuffer,
)
from roboflow_workflows.execution_engine.v2.errors import (
    ContractError,
    WorkflowExecutionError,
)
from roboflow_workflows.execution_engine.v2.execution.inputs import kinds_named
from roboflow_workflows.execution_engine.v2.execution.steps import RunState
from roboflow_workflows.execution_engine.v2.kinds import WILDCARD_KIND_NAME, Kind
from roboflow_workflows.execution_engine.v2.plan import (
    ChildInputPort,
    ChildOutputPort,
    CompiledWorkflow,
    InputPort,
    PlannedWorkflowOutput,
    RunResult,
    Source,
    StepPort,
)


@dataclass(frozen=True)
class SelectedPort:
    """One port selected by a workflow output.

    Args:
        output: The workflow output declaration.
        port: The selected source: workflow input, step output, nested
            workflow input or constant.
        selector: Selector text of this port.
        key: Entry key in ``RunResult``.
        name: Key of the port inside a wildcard row value; ``None`` otherwise.
        layout: Layout of the port.
        kind_names: Declared kinds of the port.
    """

    output: PlannedWorkflowOutput
    port: Source
    selector: str
    key: str
    name: Optional[str]
    layout: EntryLayout
    kind_names: Tuple[str, ...]


def selected_ports(plan: CompiledWorkflow) -> List[SelectedPort]:
    """List the ports selected by the plan's workflow outputs, in order.

    Args:
        plan: Compiled plan.

    Returns:
        One item per selected port; wildcard outputs expand to every output
        of their step.
    """
    ports: List[SelectedPort] = []
    for output in plan.outputs:
        source = output.source
        if not isinstance(source, StepPort):
            layout, kind_names = _declared(plan, source)
            ports.append(
                SelectedPort(
                    output=output,
                    port=source,
                    selector=output.selector,
                    key=output.name,
                    name=None,
                    layout=layout,
                    kind_names=kind_names,
                )
            )
            continue

        producer = plan.step(source.step)
        wildcard = source.output == "*"
        names = list(producer.outputs) if wildcard else [source.output]
        for name in names:
            planned = producer.outputs[name]
            ports.append(
                SelectedPort(
                    output=output,
                    port=StepPort(step=source.step, output=name),
                    selector=(
                        output.selector[:-1] + name if wildcard else output.selector
                    ),
                    key=f"{output.name}/{name}" if wildcard else output.name,
                    name=name if wildcard else None,
                    layout=planned.layout,
                    kind_names=planned.kinds,
                )
            )

    return ports


def _declared(
    plan: CompiledWorkflow, source: Source
) -> Tuple[EntryLayout, Tuple[str, ...]]:
    """Layout and kinds of a non-step output source.

    A nested workflow input forwarded directly keeps the child's declared
    kinds, so their output hooks apply (decision 021).
    """
    if isinstance(source, InputPort):
        planned_input = plan.inputs[source.name]
        return planned_input.layout, planned_input.kinds
    if isinstance(source, ChildInputPort):
        child_input = plan.child_input(source)
        return child_input.layout, child_input.kinds
    if isinstance(source, ChildOutputPort):
        # A gated child output keeps its source's kinds; only the layout is
        # the effective one (decision 026).
        child_output = plan.child_output(source)
        kind_names = _source_kinds(plan, child_output.source)
        return child_output.layout, kind_names

    return EntryLayout(), (WILDCARD_KIND_NAME,)


def _source_kinds(plan: CompiledWorkflow, source: Source) -> Tuple[str, ...]:
    if isinstance(source, StepPort):
        return plan.step(source.step).outputs[source.output].kinds

    _, kind_names = _declared(plan, source)

    return kind_names


def build_result(run: RunState) -> RunResult:
    """Assemble the ``RunResult`` of a finished run.

    Args:
        run: State after the last step.

    Returns:
        Selected port entries, statuses, filtered paths and the trace.
    """
    plan = run.plan
    selections: Dict[str, Dict[str, str]] = {output.name: {} for output in plan.outputs}
    statuses: Dict[str, str] = {}
    filtered_paths: Dict[str, Tuple[Index, ...]] = {}
    data: Dict[str, Any] = {}
    layouts: Dict[str, EntryLayout] = {}
    metadata: Dict[str, Any] = {}
    input_row_count = 0
    for port in selected_ports(plan):
        entry = run.entry_for(port.port)
        if (
            port.layout.depth
            and plan.axis_origin(port.layout.axis_ids[0]).kind == "input"
        ):
            known_rows = entry.children.get((), ())
            input_row_count = max(
                input_row_count,
                max((index[0] + 1 for index in known_rows), default=0),
            )

        selections[port.output.name][port.selector] = port.key
        filtered_paths[port.key] = entry.minimal_filtered_paths()
        if entry.is_effectively_filtered():
            statuses[port.key] = "filtered"
            continue

        statuses[port.key] = "complete"
        data[port.key] = entry.to_tree()
        layouts[port.key] = entry.layout
        metadata[port.key] = entry.surviving_metadata()

    run.record("run_finished", statuses=dict(statuses))
    result = RunResult(
        outputs=WorkflowsBuffer(
            lineage_id=f"run:{run.run_id}",
            pulse_id=0,
            data=data,
            layout=layouts,
            metadata=metadata,
        ),
        selections=selections,
        statuses=statuses,
        filtered_paths=filtered_paths,
        plan=plan,
        session_id=run.session.session_id,
        run_id=run.run_id,
        trace=tuple(run.trace),
        input_row_count=input_row_count,
    )

    return result


def build_rows(result: RunResult, *, serialize: bool) -> List[Dict[str, Any]]:
    """Build V1-shaped rows from a run result.

    Args:
        result: Result of one run.
        serialize: Whether to apply the kinds' serializers.

    Returns:
        One mapping per index of the workflow-input axis, or a single mapping
        when no output follows a workflow-input axis.

    Raises:
        WorkflowExecutionError: When outputs follow two different workflow
            input axes, or a kind hook fails for every declared kind.
    """
    plan = result.plan
    ports = selected_ports(plan)
    projections = {
        port.key: _project(result, port, serialize=serialize) for port in ports
    }
    row_axes = {
        port.layout.axis_ids[0]
        for port in ports
        if port.layout.depth
        and plan.axis_origin(port.layout.axis_ids[0]).kind == "input"
    }
    if len(row_axes) > 1:
        raise WorkflowExecutionError(
            f"Workflow outputs follow independent input axes {sorted(row_axes)}; V1 "
            "rows need one top-level axis. Read RunResult.outputs instead"
        )

    by_output: Dict[str, List[SelectedPort]] = {
        output.name: [] for output in plan.outputs
    }
    for port in ports:
        by_output[port.output.name].append(port)

    row_axis = next(iter(row_axes), None)
    if row_axis is None:
        row = {
            name: _row_value(output_ports, projections, row=None, row_axis=None)
            for name, output_ports in by_output.items()
        }
        return [row]

    row_count = max(
        (
            len(projections[port.key])
            for port in ports
            if port.layout.axis_ids[:1] == (row_axis,)
        ),
        default=0,
    )
    row_count = max(row_count, result.input_row_count)
    rows = [
        {
            name: _row_value(output_ports, projections, row=row, row_axis=row_axis)
            for name, output_ports in by_output.items()
        }
        for row in range(row_count)
    ]
    if rows:
        return rows

    # V1: without input rows, outputs of generated axes still form one row.
    generated = {
        name: _row_value(output_ports, projections, row=None, row_axis=row_axis)
        for name, output_ports in by_output.items()
        if output_ports
        and all(
            port.layout.depth and port.layout.axis_ids[0] != row_axis
            for port in output_ports
        )
    }
    rows = [generated] if generated else []

    return rows


def _row_value(
    ports: Sequence[SelectedPort],
    projections: Mapping[str, Any],
    *,
    row: Optional[int],
    row_axis: Optional[str],
) -> Any:
    """Value of one workflow output in one row (``row=None``: whole value)."""
    per_row = {
        port.key: _port_row(port, projections[port.key], row=row, row_axis=row_axis)
        for port in ports
    }
    if not ports:
        # A wildcard over a step without outputs.
        return {}
    if ports[0].name is None:
        # A plain output selects exactly one port.
        return per_row[ports[0].key]

    common = _common_depth([port.layout for port in ports])
    follows_row = row is not None and common and ports[0].layout.axis_ids[0] == row_axis
    levels = common - 1 if follows_row else common
    merged = _merge({port.name: per_row[port.key] for port in ports}, levels=levels)

    return merged


def _port_row(
    port: SelectedPort, projection: Any, *, row: Optional[int], row_axis: Optional[str]
) -> Any:
    if row is None or not port.layout.depth or port.layout.axis_ids[0] != row_axis:
        return projection
    if row < len(projection):
        return projection[row]

    return None if port.layout.depth == 1 else []


def _common_depth(layouts: Sequence[EntryLayout]) -> int:
    depth = 0
    for axis_ids in zip(*(layout.axis_ids for layout in layouts)):
        if len(set(axis_ids)) > 1:
            break
        depth += 1

    return depth


def _merge(values: Mapping[str, Any], *, levels: int) -> Any:
    """Zip port values over ``levels`` shared axes into dicts at the leaves."""
    if levels == 0:
        if all(value is None for value in values.values()):
            return None
        return dict(values)

    size = max(
        (len(value) for value in values.values() if isinstance(value, list)), default=0
    )
    merged = [
        _merge(
            {
                name: (
                    value[position]
                    if isinstance(value, list) and position < len(value)
                    else None
                )
                for name, value in values.items()
            },
            levels=levels - 1,
        )
        for position in range(size)
    ]

    return merged


def _project(result: RunResult, port: SelectedPort, *, serialize: bool) -> Any:
    """Nested Python value of one port: lists per axis, converted leaves."""
    kinds = kinds_named(result.plan, port.kind_names)
    depth = port.layout.depth
    filtered = set(result.filtered_paths[port.key])
    present = port.key in result.outputs.data

    def convert(payload: Any) -> Any:
        converted = _convert(
            kinds,
            payload,
            options=port.output.options,
            serialize=serialize,
            location=port.selector,
        )
        return converted

    if not depth:
        return convert(result.outputs.data[port.key]) if present else None

    children: Dict[Index, Set[Index]] = {}
    leaves: Dict[Index, Any] = {}
    if present:
        _collect(
            result.outputs.data[port.key], children=children, leaves=leaves, depth=depth
        )
    # A filtered path also proves that its ancestors exist, even when the
    # whole entry is absent from the buffer.
    for path in filtered:
        for length in range(1, len(path) + 1):
            children.setdefault(path[: length - 1], set()).add(path[:length])

    def node(index: Index) -> Any:
        is_leaf = len(index) == depth
        if any(index[:length] in filtered for length in range(len(index) + 1)):
            return None if is_leaf else []
        if is_leaf:
            return convert(leaves[index]) if index in leaves else None

        known = children.get(index, ())
        size = max((child[-1] for child in known), default=-1) + 1
        nested = [node(index + (position,)) for position in range(size)]
        return nested

    projection = node(())

    return projection


def _collect(
    tree: Batch,
    *,
    children: Dict[Index, Set[Index]],
    leaves: Dict[Index, Any],
    depth: int,
) -> None:
    children[tree.parent_index] = set(tree.indices)
    for index, child in tree.iter_with_indices():
        if len(index) == depth:
            leaves[index] = child
        else:
            _collect(child, children=children, leaves=leaves, depth=depth)


def _convert(
    kinds: Sequence[Kind],
    payload: Any,
    *,
    options: Mapping[str, Any],
    serialize: bool,
    location: str,
) -> Any:
    converted = _apply_kind_hook(
        kinds,
        payload,
        hook="convert_output",
        call=lambda kind, value: kind.to_output(value, options=options),
        location=location,
    )
    if serialize:
        converted = _apply_kind_hook(
            kinds,
            converted,
            hook="serialize",
            call=lambda kind, value: kind.to_serialized(value),
            location=location,
        )

    return converted


def _apply_kind_hook(
    kinds: Sequence[Kind],
    payload: Any,
    *,
    hook: str,
    call: Callable[[Kind, Any], Any],
    location: str,
) -> Any:
    """First successful hook wins; a hook-free fallback must accept the payload."""
    if payload is None:
        return None

    hooked = [kind for kind in kinds if getattr(kind, hook) is not None]
    if not hooked:
        return payload

    failures = []
    for kind in hooked:
        try:
            converted = call(kind, payload)
        except Exception as error:
            failures.append((kind.name, error))
            continue
        return converted

    for kind in kinds:
        if getattr(kind, hook) is not None:
            continue

        try:
            kind.check(payload)
        except ContractError as error:
            failures.append((kind.name, error))
            continue
        return payload

    details = "; ".join(
        f"{name}: {type(error).__name__}: {error}" for name, error in failures
    )
    error = WorkflowExecutionError(
        f"Output {location} ({type(payload).__name__}) failed the {hook} boundary for "
        f"every declared kind: {details}"
    )
    raise error from failures[-1][1]
