defaults:
  - logger: tensorboard

_target_: lidra.loop.Loop
module: ???
dataloaders: ???

num_nodes: ${compute.n_nodes}
strategy: ${strategy}

# take all available GPUs by default
accelerator: auto
devices: auto

precision: null # default precision to whatever the model use for init
callbacks:
  _target_: lidra.config.utils.make_list_from_kwargs
plugins: null
fast_dev_run: false

max_epochs: -1 # infinite
min_epochs: null
max_steps: -1 # infinite
min_steps: null

limit_train_batches: null
limit_val_batches: null
limit_test_batches: null
limit_predict_batches: null

val_check_interval: null

profiler: null
detect_anomaly: false
enable_checkpointing: true
enable_progress_bar: true
enable_model_summary: true
deterministic: null
benchmark: false

sync_batchnorm: false

accumulate_grad_batches: 1
gradient_clip_val: null
gradient_clip_algorithm: norm

log_every_n_steps: 1 # 50 steps by default if null

