_target_: lidra.callback.tdfy.compute_metrics.TdfySingleTrialMetricsCallback
output_dir: ${hydra:runtime.output_dir}/validation_metrics_tdfy
evaluation_fn:
  _target_: lidra.callback.tdfy.compute_metrics.TdfyPerSample.evaluate
  occupancy_volume_resolution: null
  _partial_: true
batch_preprocess_fn:
  _target_: lidra.callback.tdfy.compute_metrics.TdfySingleTrialMetricsCallback.em_batch_preprocess_fn
  module_extractor_str: ???
  _partial_: true
sample_extractor_fn:
  occupancy_volume: occupancy_volume
prediction_extractor_fn:
  occupancy_volume: x_shape
metrics_fstem: metrics