_target_: lidra.callback.tdfy.compute_metrics.TdfySingleTrialMetricsCallback
output_dir: ${hydra:runtime.output_dir}/validation_metrics_tdfy
evaluation_fn:
  _target_: lidra.callback.tdfy.compute_metrics.TdfyPerSample.evaluate
  _partial_: true
  occupancy_volume_resolution: null
batch_preprocess_fn:
  _target_: lidra.callback.tdfy.compute_metrics.TdfySingleTrialMetricsCallback.em_batch_preprocess_fn
  _partial_: true
  module_extractor_str: ???
sample_extractor_fn:
  occupancy_volume: occupancy_volume
  instance_quaternion_l2c: instance_quaternion_l2c
  instance_position_l2c: instance_position_l2c
  instance_scale_l2c: instance_scale_l2c
  scene_scale: pointmap_scale
  scene_shift: pointmap_shift
prediction_extractor_fn:
  occupancy_volume: x_shape
  x_instance_rotation: x_instance_rotation
  x_instance_translation: x_instance_translation
  x_instance_scale: x_instance_scale
  x_translation_scale: x_translation_scale
  pose_target_convention: pose_target_convention
metrics_fstem: metrics