import os

PROD_ENVIRONMENT_NAME = "prod"
ROBOFLOW_ENVIRONMENT = os.getenv("ROBOFLOW_ENVIRONMENT", PROD_ENVIRONMENT_NAME)
ROBOFLOW_API_HOST = os.getenv(
    "ROBOFLOW_API_HOST",
    (
        "https://api.roboflow.com"
        if ROBOFLOW_ENVIRONMENT == PROD_ENVIRONMENT_NAME
        else "https://api.roboflow.one"
    ),
)
ROBOFLOW_API_KEY = os.getenv("ROBOFLOW_API_KEY", None)
HTTP_CODES_TO_RETRY = {408, 429, 500, 502, 503, 504}
YOLO_MODELS_MIN_DYNAMIC_BATCH_SIZE = int(
    os.getenv("YOLO_MODELS_MIN_DYNAMIC_BATCH_SIZE", "1")
)
YOLO_MODELS_OPT_DYNAMIC_BATCH_SIZE = int(
    os.getenv("YOLO_MODELS_OPT_DYNAMIC_BATCH_SIZE", "8")
)
YOLO_MODELS_MAX_DYNAMIC_BATCH_SIZE = int(
    os.getenv("YOLO_MODELS_MAX_DYNAMIC_BATCH_SIZE", "16")
)
YOLO_MODELS_WORKSPACE_SIZE = int(os.getenv("YOLO_MODELS_WORKSPACE_SIZE", "12"))
RFDETR_MODELS_MIN_DYNAMIC_BATCH_SIZE = int(
    os.getenv("RFDETR_MODELS_MIN_DYNAMIC_BATCH_SIZE", "1")
)
RFDETR_MODELS_OPT_DYNAMIC_BATCH_SIZE = int(
    os.getenv("RFDETR_MODELS_OPT_DYNAMIC_BATCH_SIZE", "8")
)
RFDETR_MODELS_MAX_DYNAMIC_BATCH_SIZE = int(
    os.getenv("RFDETR_MODELS_MAX_DYNAMIC_BATCH_SIZE", "16")
)
RFDETR_MODELS_WORKSPACE_SIZE = int(os.getenv("RFDETR_MODELS_WORKSPACE_SIZE", "12"))
RESNET_MODELS_MIN_DYNAMIC_BATCH_SIZE = int(
    os.getenv("RESNET_MODELS_MIN_DYNAMIC_BATCH_SIZE", "1")
)
RESNET_MODELS_OPT_DYNAMIC_BATCH_SIZE = int(
    os.getenv("RESNET_MODELS_OPT_DYNAMIC_BATCH_SIZE", "8")
)
RESNET_MODELS_MAX_DYNAMIC_BATCH_SIZE = int(
    os.getenv("RESNET_MODELS_MAX_DYNAMIC_BATCH_SIZE", "128")
)
RESNET_MODELS_WORKSPACE_SIZE = int(os.getenv("RESNET_MODELS_WORKSPACE_SIZE", "12"))
VIT_MODELS_MIN_DYNAMIC_BATCH_SIZE = int(
    os.getenv("VIT_MODELS_MIN_DYNAMIC_BATCH_SIZE", "1")
)
VIT_MODELS_OPT_DYNAMIC_BATCH_SIZE = int(
    os.getenv("VIT_MODELS_OPT_DYNAMIC_BATCH_SIZE", "8")
)
VIT_MODELS_MAX_DYNAMIC_BATCH_SIZE = int(
    os.getenv("VIT_MODELS_MAX_DYNAMIC_BATCH_SIZE", "32")
)
VIT_MODELS_WORKSPACE_SIZE = int(os.getenv("VIT_MODELS_WORKSPACE_SIZE", "12"))
DEEP_LAB_MODELS_MIN_DYNAMIC_BATCH_SIZE = int(
    os.getenv("DEEP_LAB_MODELS_MIN_DYNAMIC_BATCH_SIZE", "1")
)
DEEP_LAB_MODELS_OPT_DYNAMIC_BATCH_SIZE = int(
    os.getenv("DEEP_LAB_MODELS_OPT_DYNAMIC_BATCH_SIZE", "8")
)
DEEP_LAB_MODELS_MAX_DYNAMIC_BATCH_SIZE = int(
    os.getenv("DEEP_LAB_MODELS_MAX_DYNAMIC_BATCH_SIZE", "32")
)
DEEP_LAB_MODELS_WORKSPACE_SIZE = int(os.getenv("DEEP_LAB_MODELS_WORKSPACE_SIZE", "12"))
KEYPOINT_DETECTION_TASK_TYPE = "keypoint-detection"
INFERENCE_CONFIG_FILE = "inference_config.json"
CLASS_NAMES_FILE = "class_names.txt"
WEIGHTS_ONNX_FILE = "weights.onnx"
KEYPOINTS_METADATA_FILE = "keypoints_metadata.json"
TRT_CONFIG_FILE = "trt_config.json"
ENGINE_PLAN_FILE = "engine.plan"
MODEL_CONFIG_FILE = "model_config.json"
