from typing import Optional

from pydantic import BaseModel, Field


class PaliGemmaInferenceResponse(BaseModel):
    response: str = Field(description="Text generated by PaliGemma")
    time: Optional[float] = Field(
        None,
        description="The time in seconds it took to produce the response including preprocessing",
    )
