"""Stable IDs for YOLO26 depth ONNX inference-path implementations."""

from inference_models.models.optimization.ids import BASE_IMPLEMENTATION_ID

YOLO26_DEPTH_ONNX_SCHEDULER_BASE = BASE_IMPLEMENTATION_ID
YOLO26_DEPTH_ONNX_SCHEDULER_ORT_CUDA_GRAPH_V1 = "ort-cuda-graph-v1"
YOLO26_DEPTH_ONNX_SCHEDULER_ENV_NAME = "INFERENCE_MODELS_YOLO26_DEPTH_ONNX_SCHEDULER"
