"""Stable implementation IDs for YOLO26 depth-estimation stages."""

YOLO26_DEPTH_PREPROCESSOR_BASE = "base"
YOLO26_DEPTH_PREPROCESSOR_TRITON_CV2_RESIZE_FUSED_CONVERT_V1 = (
    "triton-cv2-resize-fused-convert-v1"
)
YOLO26_DEPTH_POSTPROCESSOR_BASE = "base"
YOLO26_DEPTH_POSTPROCESSOR_TRITON_AA_RESIZE_V1 = "triton-aa-resize-v1"
YOLO26_DEPTH_POSTPROCESSOR_TRITON_AA_RESIZE_EXACT_V2 = "triton-aa-resize-exact-v2"
YOLO26_DEPTH_POSTPROCESSOR_TRITON_AA_RESIZE_EXACT_FUSED_V3 = (
    "triton-aa-resize-exact-fused-v3"
)
YOLO26_DEPTH_PREPROCESSOR_ENV_NAME = "INFERENCE_MODELS_YOLO26_DEPTH_PREPROCESSOR"
YOLO26_DEPTH_POSTPROCESSOR_ENV_NAME = "INFERENCE_MODELS_YOLO26_DEPTH_POSTPROCESSOR"
