"""Stable implementation IDs for YOLO26 depth-estimation stages."""

YOLO26_DEPTH_POSTPROCESSOR_BASE = "base"
YOLO26_DEPTH_POSTPROCESSOR_TRITON_AA_RESIZE_V1 = "triton-aa-resize-v1"
YOLO26_DEPTH_POSTPROCESSOR_TRITON_AA_RESIZE_EXACT_V2 = "triton-aa-resize-exact-v2"
YOLO26_DEPTH_POSTPROCESSOR_ENV_NAME = "INFERENCE_MODELS_YOLO26_DEPTH_POSTPROCESSOR"
