# @package _global_
# Base configuration for v3 direct instantiation

# Unified save directory
save_dir: null  # null means console output only

# Processor instantiation (to be specified by specific configs)
processor:
  _target_: ???  # Must be specified by inheriting configs

# Config instantiation
config:
  _target_: ???  # Must be specified by inheriting configs
  
  # Common settings
  output_directory: ${save_dir}
  console_format: rich
  verbose: false
  quiet: false
  format_precision: 6
  extract_data_log_file: extract_data.json

# Hydra settings
hydra:
  job:
    chdir: false
  output_subdir: ${rv.if_not_none:${save_dir},.hydra,null}
  run:
    dir: ${rv.if_not_none:${save_dir},${save_dir},.}