# @package _global_
defaults:
  ## base setup
  - /run/train: base

  ## loop setup
  - /loop: mock
  # dataset setup
  - /data/module@loop.dataloaders: cifar10

  ## training module setup
  - /model/module/mock@module: classification

  # module setup
  - /model/backbone/mock@module.model.backbone: cnn
  - /optimizer@module.model.optimizer: sgd

  - _self_

module:
  model:
    _target_: lidra.model.module.base.TrainableBackbone
