defaults:
  - metrics@compute_metrics_callback: validation_shape_and_pose
  - _self_

_target_: lidra.model.module.tdfy.generative.FeaturesAndPoseToken
generator: ???
batch_conditions_mapping: ???
batch_preprocessing_fn: 
  _target_: lidra.model.module.tdfy.generative.FeaturesAndPoseToken._prepare_training_targets
  _partial_: true
compute_metrics_callback:
  batch_preprocess_fn:
    module_extractor_str: _base_models.decoder