defaults:
  - metrics@compute_metrics_callback: validation_shape_only
  - _self_

_target_: lidra.model.module.tdfy.generative.FeaturesOnly
generator: ???
batch_conditions_mapping: ???
compute_metrics_callback:
  batch_preprocess_fn:
    module_extractor_str: _base_models.decoder