_target_: lidra.model.module.tdfy.generative.Generative
generator: ???
encoder: null
decoder: null
batch_encoder_input_mapping: "input"
batch_decoder_input_mapping: ??? # use ${rv.locate:lidra.data.utils.empty_mapping} to provide empty arguments
batch_conditions_mapping: ???
batch_preprocessing_fn: null
