_target_: lidra.model.module.tdfy.vae.SparseStructureVAE
encoder: 
  _target_: lidra.model.module.base.TrainableBackbone
  backbone: 
    _target_: lidra.model.backbone.trellis.models.sparse_structure_vae.SparseStructureEncoderTdfyWrapper
    in_channels: 1
    latent_channels: 8
    num_res_blocks: 2
    num_res_blocks_middle: 2
    channels: [32, 128, 512]
    use_fp16: true
  optimizer: ???
decoder: 
  _target_: lidra.model.module.base.TrainableBackbone
  backbone:
    _target_: lidra.model.backbone.trellis.models.sparse_structure_vae.SparseStructureDecoderTdfyWrapper
    out_channels: 1
    latent_channels: 8
    num_res_blocks: 2
    num_res_blocks_middle: 2
    channels: [512, 128, 32]
    use_fp16: true
    reshape_input_to_cube: false
  optimizer: ???
