# This is a config for E2B sandbox template.
# You can use template ID (qfupheopqmf6w7b36h6o) or template name (roboflow-inference-sandbox-v0-51-10) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("roboflow-inference-sandbox-v0-51-10") # Sync sandbox
# sandbox = await AsyncSandbox.create("roboflow-inference-sandbox-v0-51-10") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('roboflow-inference-sandbox-v0-51-10')

team_id = "1647872e-e6b7-4797-8e30-d1cd5dbcb671"
start_cmd = "docker/e2b/e2b.toml"
dockerfile = "docker/e2b/e2b.Dockerfile"
template_name = "inference-sandbox-v"
template_id = "qfupheopqmf6w7b36h6o"
