[pytest]
testpaths = tests inference_models/tests
addopts = --import-mode=importlib
pythonpath = . inference_models
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    workflows: marks tests that run workflows (deselect with '-m "not workflows"')
