# @package _global_
defaults:
  - fm-trellis-trellis500k

  # load pretrained backbone
  - /data/dataset/tdfy/trellis500k/preprocessor@tdfy.preprocessor: train_keep_bg

  - override /model/backbone/dit/embedder@tdfy.reverse_fn.condition_embedder: image_mask_dino_dino
  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_fo_v1

module:
  batch_conditions_mapping: ["image", "mask"] # cropped image, cropped mask
  generator:
    backbone:
      reverse_fn:
        unconditional_handling: "add_flag"

lr: 1e-4  # Smaller learning rate; tune yourself

loop:
  max_epochs: 100
  dataloaders:
    validation: null
    training:
      dataset:
        # _target_: torch.utils.data.dataset.ConcatDataset
        datasets:
          # _target_: lidra.config.utils.make_list_from_kwargs
          variantF_v1:
            preprocessor: ${tdfy.preprocessor}
          variantF_v1_complement: 
            preprocessor: ${tdfy.preprocessor}

tdfy:
  reverse_fn:
    force_zeros_cond: True