# @package _global_
defaults:
  - fm-trellis-trellis500k-randPad-ema
  - _self_

loop:
  precision: null
  callbacks:
    gradient_scaler:
      _target_: lidra.callback.tdfy.gradual_grad_scale.GradualGradScaleCallback
      initial_scale: 30.0
      scale_growth: 0.001
    gradient_clipping:
      _target_: lidra.callback.tdfy.adaptive_gradient_clipping.AdaptiveGradientClipCallback
      max_clip_val: 1.0
      clip_percentile: 95.0
      buffer_size: 1000
  # dataloaders:
  #   validation: null
    
module:
  generator:
    backbone:
      training_time_sampler_fn:
        _target_: lidra.model.backbone.generator.flow_matching.model.lognorm_sampler
        _partial_: true
        mean: -1.0
        std: 1.0 

tdfy:
  reverse_fn:
    use_fp16: True