# @package _global_
defaults:
  - fm-trellis-trellis500k-tricks-moge-mm
  - override /model/backbone@tdfy.reverse_fn: trellis_dit/mot_image_large_shape_6drotation_normalized
  - override /model/backbone/dit/embedder@tdfy.reverse_fn.condition_embedder: image_dino_embedder_fuser 
  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_v6

module:
  decoder:
    backbone:
      pretrained_ckpt_path: ${cluster.path.weights}/tdfy/trellis-ss-vae-trial1-lambda1e-3-8x8/weiyao_decoder.ckpt
  _target_: lidra.model.module.tdfy.generative.FeaturesAndPoseTokenWithNormalization
  keep_preds: ["shape", "6drotation_normalized"]
  generator:
    backbone:
      loss_weights:
        # help optree broadcase, it does not broadcast DictConfig
        _target_: lidra.config.utils.make_dict
        shape: 1.0
        6drotation_normalized: 0.1

loop:
  dataloaders:
    validation: null
    training:
      dataset:
        datasets:
          # ObjaverseXL_github_all:
          #   latent_dir: ${tdfy.latent_dir}
          ABO:
            latent_dir: ${tdfy.latent_dir}
          HSSD:
            latent_dir: ${tdfy.latent_dir}
          ObjaverseXL_github:
            latent_dir: ${tdfy.latent_dir}
          ObjaverseXL_sketchfab_all:
            latent_dir: ${tdfy.latent_dir}
          shutterstock_3d:
            latent_dir: ${tdfy.latent_dir}

tdfy:
  latent_dir: "ss_latents/trellis-ss-vae-trial1-lambda1e-3-8x8"