# @package _global_
defaults:
  - fm-trellis-trellis500k-tricks-moge-mm
  - override /model/backbone@tdfy.reverse_fn: trellis_dit/mm_image_large_shape_quaternion
  
module:
  keep_preds: ["shape", "quaternion"]
  generator:
    backbone:
      loss_weights:
        # help optree broadcase, it does not broadcast DictConfig
        _target_: lidra.config.utils.make_dict
        shape: 1.0
        quaternion: 0.01