# @package _global_
defaults:
  - fm-trellis-trellis500k-tricks-moge-mm
  - override /model/backbone@tdfy.reverse_fn: trellis_dit/mm_image_large_shape_6drotation

module:
  keep_preds: ["shape", "6drotation"]
  generator:
    backbone:
      loss_weights:
        # help optree broadcase, it does not broadcast DictConfig
        _target_: lidra.config.utils.make_dict
        shape: 1.0
        6drotation: 0.01