# @package _global_
defaults:
  - fm-trellis-trellis500k-tricks-moge
  - override /model/backbone@tdfy.reverse_fn: trellis_dit/mm_unified_image_large_shape_only
  - override /model/backbone/dit/embedder@tdfy.reverse_fn.condition_embedder: unified_image_dino_moge
  - override /model/module/tdfy@module: generative-featuresAndPoseToken
  - _self_


module:
  keep_preds: ["shape"]
  generator:
    backbone:
      loss_weights:
        # help optree broadcase, it does not broadcast DictConfig
        _target_: lidra.config.utils.make_dict
        shape: 1.0