# @package _global_
defaults:
  - base

  # generator
  - /model/backbone@tdfy.reverse_fn: trellis_dit/image_large_featured_latents_trellis_pretrained

  - override /model/module/tdfy@module: generative-trellisDino-features-only
  - override /model/backbone/generator@module.generator.backbone: flow_matching_cfg

  # dataset
  - override /data/module@loop.dataloaders: tdfy/trellis500k

  - _self_

batch_size: 4


module:
  batch_conditions_mapping: ["image", "coords"] # rgb-image
  # deterministic_sampling: True
  generator:
    backbone:
      reversed_timestamp: true

      reverse_fn:
        unconditional_handling: "add_flag"
        backbone: ${tdfy.reverse_fn}

loop:
  max_epochs: 40
  precision: bf16
  dataloaders:
    validation: null
    training:
      dataset:
        latent_type: features
        subsets: ["ABO", "ObjaverseXL_sketchfab", "ObjaverseXL_github"]
        max_num_voxels: 25000
        resnet_normalization: True
        tight_obj_boundary: True
        random_pad: 0.2
  callbacks:
    # device_monitor: ???
    model_checkpoint2:
      _target_: pytorch_lightning.callbacks.ModelCheckpoint
      save_on_train_epoch_end: true
      every_n_epochs: 25
      save_top_k: -1
  use_distributed_sampler: False
  # checkpoint: "/checkpoint/3dfy/weiyaowang/lidra/logs/timestamped/2025-02-07/00-50-37/0/lightning/version_0/checkpoints/last.ckpt"
  # limit_train_batches: 500

tdfy:
  collator:
    _target_: lidra.data.collator.auto_collate
  reverse_fn:
    model:
      condition_embedder: 
        dino_model: "dinov2_vitl14_reg"
        input_size: 518
        prenorm_features: True
        normalize_images: False
