# @package _global_
defaults:
  - fm-trellis-features-trellis500k-tricks-inHouseVAE

# batch_size: 4

loop:
  max_epochs: 800
  precision: null

module:
  generator:
    backbone:
      training_time_sampler_fn:
        _target_: lidra.model.backbone.generator.flow_matching.model.lognorm_sampler
        _partial_: true
        mean: -1.0
        std: 1.0 
      reverse_fn:
        strength: 0.0
      inference_steps: 12