# @package _global_
defaults:
  - fm-trellis-trellis500k-tricks
  - override /model/backbone/dit/embedder@tdfy.reverse_fn.condition_embedder: image_dino_moge
  - _self_
  

loop:
  precision: null
  dataloaders:
    validation: null
    
module:
  batch_conditions_mapping: 
    image: image
  generator:
    backbone:
      reverse_fn:
        unconditional_handling: "add_flag"
      training_time_sampler_fn:
        _target_: lidra.model.backbone.generator.flow_matching.model.lognorm_sampler
        _partial_: true
        mean: -1.0
        std: 1.0 
