# @package _global_
# Base configuration for v3 multi-trial analysis with direct instantiation
defaults:
  - ../base
  - _self_

# Processor instantiation
processor:
  _target_: lidra.metrics.analysis.v3.processor.multi_trial.MultiTrialProcessor

# Config instantiation
config:
  _target_: lidra.metrics.analysis.v3.processor.multi_trial.MultiTrialConfig
  
  # Required
  input_file: ???
  
  # Metrics to analyze - must be specified by inheriting configs
  metrics:
    _target_: lidra.metrics.analysis.v3.processor.multi_trial.Metric.make_metrics_dict
  
  # Default settings
  thresholds: {}
  trial_reduction_fns: {}
  trial_reduction_mode: mean
  
  # Data cleaning
  drop_na: true
  drop_na_columns: null
  drop_incomplete_trials: true
  max_trials: null
  
  # Statistics
  statistics:
    - mean
    - std
    - p5
    - p95

# # @package _global_
# # Default configuration for v3 multi-trial metrics analysis

# # Unified save directory - controls both processor output and hydra behavior
# save_dir: null  # null means console output only; if set, saves results.csv and logs

# processor:
#   # Input/Output
#   input_file: ???  # Required - no default
#   output_directory: ${save_dir}  # Inherits from save_dir
#   console_format: rich  # "rich" or "csv" - only used for console output

#   # Metrics to analyze - must be specified
#   metrics:
#     _target_: lidra.metrics.analysis.v3.processor.multi_trial.Metric.make_metrics_dict

#   # Threshold transformations (optional)
#   thresholds: {}

#   # Trial reduction functions
#   trial_reduction_fns: {}

#   # Trial reduction mode
#   trial_reduction_mode: mean  # could also use 'best_by_group' or 'best_independent'

#   # Data cleaning options
#   drop_na: true  # Drop rows with any missing values
#   drop_na_columns: null  # Drop rows missing values in these columns
#   drop_incomplete_trials: true  # Drop samples with incomplete trials
#   max_trials: null  # Keep only first N trials per sample

#   # Statistics to compute
#   statistics:
#     - mean
#     - std
#     - p5
#     - p95

#   # Output options
#   verbose: false  # Print cleaning statistics
#   quiet: false  # Suppress all output
#   format_precision: 6  # Number of decimal places for formatting
#   extract_data_log_file: extract_data.json  # Filename for JSON logs (saved to output_directory if specified)


# hydra:
#   job:
#     chdir: false
#   output_subdir: ${rv.if_not_none:${save_dir},.hydra,null}
#   run:
#     dir: ${rv.if_not_none:${save_dir},${save_dir},.}
