# @package _global_

# Stage1 configuration - full analysis preset using direct instantiation
defaults:
  - base
  - _self_



# Override config with stage1 metrics
config:
  drop_na: false
  drop_na_columns:
    - f1
    - chamfer_distance
    - oriented_rot_error_deg
  # All metrics from the legacy config
  metrics:
    f1:
      direction: maximize
      trial_reduction_group: shape
    chamfer_distance:
      direction: minimize
      trial_reduction_group: shape
    oriented_rot_error_deg:
      direction: minimize
      trial_reduction_group: orientation

  
  # Trial reduction functions
  trial_reduction_fns:
    orientation:
      _target_: lidra.metrics.analysis.v3.trial_reduction.select_by
      _partial_: true
      select_trials_by: oriented_chamfer_distance
      select_trials_should_be_minimized: true
    shape:
      _target_: lidra.metrics.analysis.v3.trial_reduction.select_by
      _partial_: true
      select_trials_by: chamfer_distance
      select_trials_should_be_minimized: true

  
  # Thresholds
  thresholds:
    oriented_rot_error_deg: [5, 15, 30]

  
  # More comprehensive statistics
  statistics:
    - mean
    - std
    - min
    - max
    - p5
    - p25
    - p50
    - p75
    - p95