# @package _global_
defaults:
  - /run/inference/tdfy/base
  - /model/backbone@overwrites.module.generator.backbone: generator/flow_matching_cfg_inference

module: ???

loop:
  module: ${module}
  enable_progress_bar: true
  precision: bf16

  dataloaders:
    validation:
      batch_size: ${batch_size}
      collate_fn:
        _target_: lidra.data.collator.auto_collate


logs:
  config: ${rv.config:${logs.path}/config_dictmap.yaml}

predict:
  args:
    dataloader: ${loop.dataloaders.validation}
