defaults:
  - /model/backbone/dit/embedder@condition_embedder: dino

_target_: lidra.model.backbone.trellis.models.sparse_structure_flow.SparseStructureFlowTdfyWrapper
resolution: 16
in_channels: 8
out_channels: 8
model_channels: 1024
patch_size: 1
num_blocks: 24
num_heads: 16
mlp_ratio: 4

# num_io_res_blocks: 2
# io_block_channels: [128]
pe_mode: ape
qk_rms_norm: true
use_fp16: false # better to let lightning handle this

cond_channels: 1024
