defaults: 
  - /model/backbone/trellis_dit@model: image_large_featured_latents

_target_: lidra.model.io.load_model_from_checkpoint
checkpoint_path: /home/haotang/dev/TRELLIS-image-large/ckpts/slat_flow_img_dit_L_64l8p2_fp16.safetensors
strict: False
state_dict_key: null
state_dict_fn: 
  _target_: lidra.model.io.remove_prefix_state_dict_fn
  prefix: "placeholder" 