_target_: lidra.model.io.load_model_from_checkpoint
checkpoint_path: ???
model: ???
strict: True
device: "cpu"
state_dict_fn: 
  _target_: lidra.model.io.remove_prefix_state_dict_fn
  prefix: "_base_models.generator.reverse_fn.backbone." 