# @package _global_
defaults:
  - ../midtraining/cropped-cropped-mask-midtraining

  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_trellis_unique_st3d: r3_25_trellis_unique_st3d

  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_empty


lr: 1e-5

loop:
  max_epochs: 100
  dataloaders:
    training:
      dataset:
        # _target_: torch.utils.data.dataset.ConcatDataset
        datasets:
          # _target_: lidra.config.utils.make_list_from_kwargs
          r3_25_trellis_unique_st3d:
            preprocessor: ${tdfy.preprocessor}

tdfy:
  reverse_fn:
    checkpoint_path: /checkpoint/3dfy/haotang/lidra/logs/tagged/_submit/cropped-cropped-mask-midtraining/lightning/version_0/checkpoints/epoch=24-step=129875-v1.ckpt