# @package _global_
defaults:
  - v0.2_morphing

  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_March_morphing: r3_25_March_morphing


lr: 1e-5  # Smaller learning rate; tune yourself

loop:
  max_epochs: 100
  dataloaders:
    training:
      dataset:
        datasets:
          r3_25_March_morphing:
            preprocessor: ${tdfy.preprocessor}
            metadata_fname: "metadata_clean.csv"
            metadata_filter: 
              _target_: lidra.data.dataset.tdfy.metadata_filter.custom_metadata_filter
              filter_funcs:
                - _target_: lidra.data.dataset.tdfy.metadata_filter.unique_mesh_filter
                  col_name: "sha256_prior_morphing"
                - _target_: lidra.data.dataset.tdfy.metadata_filter.data_query_filter
                  query: "mesh_source=='trellis' or mesh_source=='shutterstock'"
