# @package _global_
defaults:
  - ../fm-trellis-trellis500k-tricks-moge-mm
  - /data/dataset/tdfy/trellis500k/preprocessor@tdfy.preprocessor: train_default
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.artists_3d: artists_3d
  - /model/backbone@tdfy.reverse_fn_pretrained: trellis_dit/mm_image_large_shape_only_pretrained
  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_empty
  - override /model/backbone/dit/embedder@tdfy.reverse_fn_pretrained.model.condition_embedder: image_dino_moge

lr: 1e-5

loop:
  max_epochs: 100
  dataloaders:
    validation: null
    training:
      dataset:
        # _target_: torch.utils.data.dataset.ConcatDataset
        datasets:
          # _target_: lidra.config.utils.make_list_from_kwargs
          artists_3d:
            preprocessor: ${tdfy.preprocessor}

tdfy:
  reverse_fn_pretrained:
    # checkpoint_path: /fsx-3dfy-v2/ryanxiangli/lidra-logs/xiang-bds-catA-0.5x-lr0.02x-long-preference-test/csv/version_0/checkpoints/epoch-50-step-10506.ckpt
    checkpoint_path: /fsx-3dfy-v2/haotang/3dfy/lidra/logs/tagged/_submit/v0-tricks-moge-mm-training-v2-ft-trellis-uniq-st3d-Feb-April/lightning/version_0/checkpoints/last.ckpt
    strict: false
    device: "cpu"
    model:
      use_fp16: True
      force_zeros_cond: True
  reverse_fn: ${tdfy.reverse_fn_pretrained}
