# @package _global_
defaults:
  - ../fm-trellis-trellis500k-tricks-moge-mm
  - /data/dataset/tdfy/trellis500k/preprocessor@tdfy.preprocessor: train_default
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_sa3_April: r3_sa3_April
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_April: r3_25_April
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_March_morphing: r3_25_March_morphing
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_morphing: r3_25_morphing
  - /model/backbone@tdfy.reverse_fn_pretrained: trellis_dit/mm_image_large_shape_only_pretrained
  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_empty
  - override /model/backbone/dit/embedder@tdfy.reverse_fn_pretrained.model.condition_embedder: image_dino_moge

lr: 1e-5

loop:
  max_epochs: 100
  dataloaders:
    validation: null
    training:
      dataset:
        # _target_: torch.utils.data.dataset.ConcatDataset
        datasets:
          # _target_: lidra.config.utils.make_list_from_kwargs
          r3_sa3_April:
            preprocessor: ${tdfy.preprocessor}
          r3_25_April:
            preprocessor: ${tdfy.preprocessor}
          r3_25_March_morphing:
            preprocessor: ${tdfy.preprocessor}
          r3_25_morphing:
            preprocessor: ${tdfy.preprocessor}

tdfy:
  reverse_fn_pretrained:
    checkpoint_path: /checkpoint/3dfy/haotang/lidra/logs/tagged/_submit/v0-pretrain-tricks-moge/lightning/version_0/checkpoints/last.ckpt
    strict: false
    device: "cpu"
    model:
      use_fp16: True
      force_zeros_cond: True
  reverse_fn: ${tdfy.reverse_fn_pretrained}
