# @package _global_
defaults:
  # - ../midtraining/v2_mot_shape_6drotation_normalized_layout_ptmap_dropout.yaml
  - v2_mot_6drotation_normalized_layout_ptmap_Feb-May.yaml
  - override /model/backbone/dit/embedder@tdfy.reverse_fn_pretrained.model.condition_embedder: image_dino_mask_pointmap_embedder_fuser_w_pm_cfg
  - _self_

module:
  generator:
    scheduler:
      _target_: torch.optim.lr_scheduler.LinearLR
      _partial_: true
      start_factor: 0.01   # Start at 1% of base lr
      end_factor: 1.0      # Ramp up to 100% of base lr (full lr)
      total_iters: 1000    # Number of steps for warmup

    # Configure scheduler to update per step
    scheduler_kwargs:
      interval: step       # Update lr every step instead of epoch
      frequency: 1
      name: "train/learning_rate"

loop:
  callbacks:
    ema:
      _target_: lidra.callback.ema.EMA
      decays:
        slow: 0.9999 # trellis's rate
        medium: 0.999
        fast: 0.99
      default_decay_for_eval: slow
      device: null
      recover_existing: true
      force_fp32: true
      start_step: 5000
  deterministic: false
  dataloaders:
    validation: null
    training:
      dataset:
        datasets:
          elephant: null
          elephant_trellis500k: null
          elephant_sketchfab_extended: null
          elephant_shutterstock_tranche1: null
          elephant_shutterstock_tranche2: null
          elephant_ego: null
          elephant_food: null
          elephant_food_table: null
          r3_25_May:
            latent_dir: ${tdfy.latent_dir}
          r3_sa3_April:
            latent_dir: ${tdfy.latent_dir}
          r3_25_April:
            latent_dir: ${tdfy.latent_dir}
          r3_25_March_morphing:
            latent_dir: ${tdfy.latent_dir}
          r3_25_morphing:
            latent_dir: ${tdfy.latent_dir}

tdfy:
  latent_dir: ss_latents/trellis-ss-vae-trial1-lambda1e-3-8x8
  vae_checkpoint_path: ${cluster.path.weights}/tdfy/trellis-ss-vae-trial1-lambda1e-3-8x8/weiyao_decoder.ckpt
  pointmap_embedder:
    dropout_prob: 0.1
    force_drop_modalities: null
  reverse_fn_pretrained:
    checkpoint_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/v2_mot_shape_6drotation_normalized_layout_inhouse_ptmap_cfg01-eitrV123EgoFood-try3/lightning/version_0/checkpoints/epoch=19-step=57400-v1.ckpt
    strict: false
    device: "cpu"
    model:
      use_fp16: false
      force_zeros_cond: True
