# @package _global_
defaults:
  - ../midtraining/v2_mot_shape_6drotation_normalized_layout_ptmap.yaml
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_May: r3_25_May
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_sa3_April: r3_sa3_April
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_April: r3_25_April
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_March_morphing: r3_25_March_morphing
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_morphing: r3_25_morphing
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_Sept: r3_25_Sept
  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_empty

lr: 1e-5
loop:
  callbacks:
    ema: null
  max_epochs: 200
  dataloaders:
    validation: null
    training:
      dataset:
        # _target_: torch.utils.data.dataset.ConcatDataset
        datasets:
          # _target_: lidra.config.utils.make_list_from_kwargs
          r3_25_May:
            pose_loader: ${tdfy.pose_loader}
            pointmap_loader: ${tdfy.pointmap_loader}
            preprocessor: ${tdfy.preprocessor}
            return_pointmap: True
          r3_sa3_April:
            pose_loader: ${tdfy.pose_loader}
            pointmap_loader: ${tdfy.pointmap_loader}
            preprocessor: ${tdfy.preprocessor}
            return_pointmap: True
          r3_25_April:
            pose_loader: ${tdfy.pose_loader}
            pointmap_loader: ${tdfy.pointmap_loader}
            preprocessor: ${tdfy.preprocessor}
            return_pointmap: True
          r3_25_March_morphing:
            pose_loader: ${tdfy.pose_loader}
            pointmap_loader: ${tdfy.pointmap_loader}
            preprocessor: ${tdfy.preprocessor}
            return_pointmap: True
          r3_25_morphing:
            pose_loader: ${tdfy.pose_loader}
            pointmap_loader: ${tdfy.pointmap_loader}
            preprocessor: ${tdfy.preprocessor}
            return_pointmap: True
          r3_25_Sept:
            pose_loader: ${tdfy.pose_loader}
            pointmap_loader: ${tdfy.pointmap_loader}
            preprocessor: ${tdfy.preprocessor}
            return_pointmap: True
tdfy:
  pose_weight: 0.1
  reverse_fn_pretrained:
    # checkpoint_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/v2_mot_shape_6drotation_normalized_layout_ptmap/lightning/version_0/checkpoints/epoch=49-step=63150-v1.ckpt
    checkpoint_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/v2_mot_shape_6drotation_normalized_layout_ptmap-normalized-eitrv1/lightning/version_0/checkpoints/epoch=99-step=56700-v1.ckpt
    strict: false
    device: "cpu"
    model:
      use_fp16: False
      force_zeros_cond: True
  reverse_fn: ${tdfy.reverse_fn_pretrained}
  pose_loader:
    _target_: lidra.data.dataset.tdfy.trellis.pose_loader.R3.load_pose
    _partial_: True
  pointmap_loader:
    _target_: lidra.data.dataset.tdfy.trellis.pose_loader.R3.load_pointmap
    _partial_: True
    pointcloud_directory: "/checkpoint/3dfy/shared/r3_data/pointmaps/moge"

