# @package _global_
defaults:
  - ../midtraining/v2_mot_shape_quaternion_layout_ptmap
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.scannetpp: scannetpp
  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_empty

lr: 1e-5
loop:
  max_epochs: 25
  dataloaders:
    validation: null
    training:
      dataset:
        # _target_: torch.utils.data.dataset.ConcatDataset
        datasets:
          # _target_: lidra.config.utils.make_list_from_kwargs
          scannetpp:
            pose_loader: ${tdfy.pose_loader}
            pointmap_loader: ${tdfy.pointmap_loader}
            preprocessor: ${tdfy.preprocessor}
            return_pointmap: True

tdfy:
  reverse_fn_pretrained:
    checkpoint_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/v2-mot-layout-ptmap-eitrpw0_1-lr1e-5-pw0_1-fixcrop-Feb-April/lightning/version_0/checkpoints/epoch=74-step=22500-v1.ckpt
    strict: false
    device: "cpu"
    model:
      use_fp16: True
      force_zeros_cond: True
      freeze_shared_parameters: True
      condition_embedder:
        freeze: True
  reverse_fn: ${tdfy.reverse_fn_pretrained}
  pose_loader:
    _target_: lidra.data.dataset.tdfy.trellis.pose_loader.R3.load_pose
    _partial_: True
  pointmap_loader:
    _target_: lidra.data.dataset.tdfy.trellis.pose_loader.R3.load_pointmap
    _partial_: True
    pointcloud_directory: "/checkpoint/3dfy/shared/datasets/scannetpp_new/raw"
  pose_weight: 0.1

module:
  generator:
    backbone:
      reverse_fn:
        unconditional_handling: "add_flag"
      loss_weights:
        # help optree broadcase, it does not broadcast DictConfig
        _target_: lidra.config.utils.make_dict
        # layout midtraining we only train pose
        shape: 0.0
        quaternion: ${tdfy.pose_weight}
        translation: ${tdfy.pose_weight}
        scale: ${tdfy.pose_weight}
        translation_scale: ${tdfy.pose_weight}
