# @package _global_
defaults:
  # - ../midtraining/v2_mot_shape_6drotation_normalized_layout_ptmap_dropout.yaml
  - v2_mot_6drotation_normalized_layout_ptmap_Feb-May.yaml
  - /data/dataset/tdfy/trellis500k/subset_train@tdfy.training_dataset: artists_3d_posed
  - override /model/backbone/dit/embedder@tdfy.reverse_fn_pretrained.model.condition_embedder: image_dino_mask_pointmap_embedder_fuser_w_pm_cfg
  - override /data/dataset/tdfy/trellis500k/preprocessor@tdfy.val_preprocessor: val_keep_bg_pm_normTransObjScaleScene
  - override /data/dataset/tdfy/trellis500k/preprocessor@tdfy.preprocessor: train_keep_bg_pm_normTransObjScaleScene
  - _self_

module:
  generator:
    scheduler: null
    backbone:
      loss_weights:
        translation: 1.0

loop:
  max_epochs: 8
  callbacks:
    ema:
      _target_: lidra.callback.ema.EMA
      decays:
        fast: 0.995
      default_decay_for_eval: fast
      device: null
      recover_existing: true
      force_fp32: true
      start_step: 100
    model_checkpoint:
      # every_n_epochs: 1
      save_top_k: -1
    model_checkpoint2: null
  deterministic: false
  dataloaders:
    validation: null
    training:
      dataset:
        datasets:
          elephant: null
          elephant_v1_2M: null
          elephant_trellis500k: null
          elephant_sketchfab_extended: null
          elephant_shutterstock_tranche1: null
          elephant_shutterstock_tranche2: null
          elephant_ego: null
          elephant_food: null
          elephant_food_table: null
          r3_25_May: null
          r3_sa3_April: null
          r3_25_April: null
          r3_25_March_morphing: null
          r3_25_morphing: null
          artists_3d_posed: 
            _target_: lidra.data.dataset.tdfy.sampler.replicate_dataset
            dataset: ${tdfy.training_dataset}
            num_replicas: 25

tdfy:
  training_dataset:
    latent_dir: ${tdfy.latent_dir}
    pose_loader: ${tdfy.pose_loader}
    preprocessor: ${tdfy.preprocessor}
    return_pointmap: True
  latent_dir: ss_latents/trellis-ss-vae-trial1-lambda1e-3-8x8
  vae_checkpoint_path: ${cluster.path.weights}/tdfy/trellis-ss-vae-trial1-lambda1e-3-8x8/weiyao_decoder.ckpt
  pointmap_embedder:
    dropout_prob: 0.1
    force_drop_modalities: null
  reverse_fn_pretrained:
    checkpoint_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/v2_mot_shape_6drotation_normalized_inhouse_vae_ptmap_dropoutCFG_Feb-May-only/lightning/version_0/checkpoints/epoch=199-step=76800-v1.ckpt
    strict: false
    device: "cpu"
    model:
      use_fp16: false
      force_zeros_cond: True