# @package _global_
defaults:
  - ../midtraining/v2_mot_shape_6drotation_normalized_layout.yaml
  - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.scannetpp: scannetpp
  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_empty

lr: 1e-5
loop:
  max_epochs: 25
  dataloaders:
    validation: null
    training:
      dataset:
        # _target_: torch.utils.data.dataset.ConcatDataset
        datasets:
          # _target_: lidra.config.utils.make_list_from_kwargs
          scannetpp:
            pose_loader: ${tdfy.pose_loader}
            pointmap_loader: ${tdfy.pointmap_loader}
            preprocessor: ${tdfy.preprocessor}

tdfy:
  pose_weight: 0.1
  reverse_fn_pretrained:
    checkpoint_path: /checkpoint/3dfy/haotang/lidra/logs/tagged/_submit/v2_mot_6drotation_normalized_Feb-May/lightning/version_0/checkpoints/epoch=99-step=76800-v1.ckpt
    strict: false
    device: "cpu"
    model:
      use_fp16: True
      force_zeros_cond: True
      freeze_shared_parameters: True
      condition_embedder:
        freeze: True

  reverse_fn: ${tdfy.reverse_fn_pretrained}
  pose_loader:
    _target_: lidra.data.dataset.tdfy.trellis.pose_loader.R3.load_pose
    _partial_: True
  pointmap_loader:
    _target_: lidra.data.dataset.tdfy.trellis.pose_loader.R3.load_pointmap
    _partial_: True
    pointcloud_directory: "/checkpoint/3dfy/shared/datasets/scannetpp_new/raw"

module:
  pose_target_convention: ScaleShiftInvariant
  keep_preds: ["shape", "6drotation_normalized", "translation", "scale", "translation_scale"]
  # cropped image, cropped mask, full image, mask
  batch_conditions_mapping: 
    image: image
    mask: mask
    rgb_image: rgb_image
    rgb_image_mask: rgb_image_mask
  generator:
    backbone:
      reverse_fn:
        unconditional_handling: "add_flag"
      loss_weights:
        # help optree broadcase, it does not broadcast DictConfig
        _target_: lidra.config.utils.make_dict
        # layout midtraining we only train pose
        shape: 0.0
        6drotation_normalized: ${tdfy.pose_weight}
        translation: ${tdfy.pose_weight}
        scale: ${tdfy.pose_weight}
        translation_scale: ${tdfy.pose_weight}
