# @package _global_
defaults:
  # - ../midtraining/v2_mot_shape_6drotation_normalized_layout_ptmap_dropout.yaml
  - v2_mot_6drotation_normalized_layout_ptmap_Feb-Sept.yaml
  # - /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.artists_3d_posed: artists_3d_posed
  # - override /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_May: r3_25_May_posefilterv4
  # - override /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_sa3_April: r3_sa3_April_posefilterv4
  # - override /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_April: r3_25_April_posefilterv4
  # - override /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_March_morphing: r3_25_March_morphing_posefilterv4
  # - override /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_morphing: r3_25_morphing_posefilterv4
  # - override /data/dataset/tdfy/trellis500k/subset_train@loop.dataloaders.training.dataset.datasets.r3_25_Sept: r3_25_Sept_posefilterv4
  - override /model/backbone/dit/embedder@tdfy.reverse_fn_pretrained.model.condition_embedder: image_dino_mask_pointmap_embedder_fuser_w_pm_cfg
  - override /data/dataset/tdfy/trellis500k/preprocessor@tdfy.val_preprocessor: val_keep_bg_pm_normTransObjScaleScene
  - override /data/dataset/tdfy/trellis500k/preprocessor@tdfy.preprocessor: train_keep_bg_pm_normTransObjScaleScene
  - _self_


module:
  generator:
    backbone:
      loss_weights:
        # help optree broadcase, it does not broadcast DictConfig
        _target_: lidra.config.utils.make_dict
        # layout midtraining we only train pose
        shape: 0.0
        6drotation_normalized: 0.1
        translation: 1.0
        scale: 0.1
        translation_scale: 0.0

loop:
  max_epochs: 100
  callbacks:
    ema:
      _target_: lidra.callback.ema.EMA
      decays:
        # slow: 0.9999 # trellis's rate
        medium: 0.999
        fast: 0.995
      default_decay_for_eval: medium
      device: null
      recover_existing: true
      force_fp32: true
      start_step: 10000
    gradient_scaler:
      _target_: lidra.callback.tdfy.gradual_grad_scale.GradualGradScaleCallback
      initial_scale: 0.0
      scale_growth: 0.0
      scale_cut: 0.0
  deterministic: false
  dataloaders:
    validation: null
    training:
      dataset:
        datasets:
          elephant: null
          elephant_trellis500k: null
          elephant_sketchfab_extended: null
          elephant_shutterstock_tranche1: null
          elephant_shutterstock_tranche2: null
          elephant_ego: null
          elephant_food: null
          elephant_food_table: null
          eitr_dataset: null
          procthor_dataset: null
          elephant_v1_2M: null
          r3_25_May:
            latent_dir: ${tdfy.latent_dir}
          r3_sa3_April:
            latent_dir: ${tdfy.latent_dir}
          r3_25_April:
            latent_dir: ${tdfy.latent_dir}
          r3_25_March_morphing:
            latent_dir: ${tdfy.latent_dir}
          r3_25_morphing:
            latent_dir: ${tdfy.latent_dir}
          r3_25_Sept:
            latent_dir: ${tdfy.latent_dir}
          # artists_3d_posed: 
          #   latent_dir: ${tdfy.latent_dir}
          #   pose_loader: ${tdfy.pose_loader}
          #   preprocessor: ${tdfy.preprocessor}
          #   return_pointmap: True

tdfy:
  latent_dir: ss_latents/trellis-ss-vae-trial1-lambda1e-3-8x8
  vae_checkpoint_path: ${cluster.path.weights}/tdfy/trellis-ss-vae-trial1-lambda1e-3-8x8/weiyao_decoder.ckpt
  pointmap_embedder:
    dropout_prob: 0.1
    force_drop_modalities: null
  reverse_fn_pretrained:
    checkpoint_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/v2-release1009-PlanA-artist1011-trweight1-filt9/lightning/version_0/checkpoints/epoch=3-step=4208.ckpt
    strict: false
    device: "cpu"
    model:
      use_fp16: false
      force_zeros_cond: True
      freeze_shared_parameters: True
      condition_embedder:
        freeze: True