import os

import torch

from inference_models.utils.environment import (
    get_boolean_from_env,
    get_comma_separated_list_of_integers_from_env,
    get_float_from_env,
    get_integer_from_env,
    parse_comma_separated_values,
)

ONNXRUNTIME_EXECUTION_PROVIDERS = parse_comma_separated_values(
    values=os.getenv(
        "ONNXRUNTIME_EXECUTION_PROVIDERS",
        "CUDAExecutionProvider,OpenVINOExecutionProvider,CoreMLExecutionProvider,CPUExecutionProvider",
    )
    .strip("[")
    .strip("]")
)
DEFAULT_DEVICE_STR = os.getenv(
    "DEFAULT_DEVICE",
    ("cuda" if torch.cuda.is_available() else "cpu"),
)
DEFAULT_DEVICE = torch.device(DEFAULT_DEVICE_STR)
ROBOFLOW_API_KEY = os.getenv("ROBOFLOW_API_KEY")
API_CALLS_TIMEOUT = get_integer_from_env(variable_name="API_CALLS_TIMEOUT", default=5)
API_CALLS_MAX_TRIES = get_integer_from_env(
    variable_name="API_CALLS_MAX_TRIES", default=3
)
IDEMPOTENT_API_REQUEST_CODES_TO_RETRY = set(
    get_comma_separated_list_of_integers_from_env(
        variable_name="IDEMPOTENT_API_REQUEST_CODES_TO_RETRY",
        default=[408, 429, 502, 503, 504],
    )
)
ROBOFLOW_ENVIRONMENT = os.getenv("ROBOFLOW_ENVIRONMENT", "prod")
ROBOFLOW_API_HOST = os.getenv(
    "ROBOFLOW_API_HOST",
    (
        "https://api.roboflow.com"
        if ROBOFLOW_ENVIRONMENT.lower() == "prod"
        else "https://api.roboflow.one"
    ),
)
RUNNING_ON_JETSON = os.getenv("RUNNING_ON_JETSON")
L4T_VERSION = os.getenv("L4T_VERSION")
INFERENCE_HOME = os.getenv("INFERENCE_HOME", "/tmp/cache")
DISABLE_INTERACTIVE_PROGRESS_BARS = get_boolean_from_env(
    variable_name="DISABLE_INTERACTIVE_PROGRESS_BARS",
    default=False,
)
LOG_LEVEL = os.getenv("LOG_LEVEL", "WARNING")
VERBOSE_LOG_LEVEL = os.getenv("VERBOSE_LOG_LEVEL", "INFO")
DISABLE_VERBOSE_LOGGER = get_boolean_from_env(
    variable_name="DISABLE_VERBOSE_LOGGER", default=False
)
AUTO_LOADER_CACHE_EXPIRATION_MINUTES = get_integer_from_env(
    variable_name="AUTO_LOADER_CACHE_EXPIRATION_MINUTES", default=1440
)
ALLOW_URL_INPUT = get_boolean_from_env(variable_name="ALLOW_URL_INPUT", default=True)
ALLOW_NON_HTTPS_URL_INPUT = get_boolean_from_env(
    variable_name="ALLOW_NON_HTTPS_URL_INPUT", default=False
)
ALLOW_URL_INPUT_WITHOUT_FQDN = get_boolean_from_env(
    variable_name="ALLOW_URL_INPUT_WITHOUT_FQDN", default=False
)

WHITELISTED_DESTINATIONS_FOR_URL_INPUT = os.getenv(
    "WHITELISTED_DESTINATIONS_FOR_URL_INPUT"
)
if WHITELISTED_DESTINATIONS_FOR_URL_INPUT is not None:
    WHITELISTED_DESTINATIONS_FOR_URL_INPUT = parse_comma_separated_values(
        WHITELISTED_DESTINATIONS_FOR_URL_INPUT
    )

BLACKLISTED_DESTINATIONS_FOR_URL_INPUT = os.getenv(
    "BLACKLISTED_DESTINATIONS_FOR_URL_INPUT"
)
if BLACKLISTED_DESTINATIONS_FOR_URL_INPUT is not None:
    BLACKLISTED_DESTINATIONS_FOR_URL_INPUT = parse_comma_separated_values(
        BLACKLISTED_DESTINATIONS_FOR_URL_INPUT
    )
ALLOW_LOCAL_STORAGE_ACCESS_FOR_REFERENCE_DATA = os.getenv(
    "ALLOW_LOCAL_STORAGE_ACCESS_FOR_REFERENCE_DATA"
)

# General model parameters defaults

INFERENCE_MODELS_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_DEFAULT_CONFIDENCE",
    default=0.4,
)
INFERENCE_MODELS_DEFAULT_IOU_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_DEFAULT_IOU_THRESHOLD",
    default=0.3,
)
INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS",
    default=300,
)
INFERENCE_MODELS_DEFAULT_CLASS_AGNOSTIC_NMS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_DEFAULT_CLASS_AGNOSTIC_NMS",
    default=False,
)
INFERENCE_MODELS_DEFAULT_MAX_NEW_TOKENS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_DEFAULT_MAX_NEW_TOKENS",
    default=4096,
)
INFERENCE_MODELS_DEFAULT_NUM_BEAMS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_DEFAULT_NUM_BEAMS",
    default=3,
)
INFERENCE_MODELS_DEFAULT_DO_SAMPLE = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_DEFAULT_DO_SAMPLE",
    default=False,
)
INFERENCE_MODELS_DEFAULT_SKIP_SPECIAL_TOKENS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_DEFAULT_SKIP_SPECIAL_TOKENS",
    default=False,
)


# Model-specific parameters defaults
INFERENCE_MODELS_DEEP_LAB_V3_PLUS_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_DEEP_LAB_V3_PLUS_DEFAULT_CONFIDENCE",
    default=0.5,
)
INFERENCE_MODELS_DINOV3_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_DINOV3_DEFAULT_CONFIDENCE",
    default=0.5,
)
INFERENCE_MODELS_EASYOCR_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_EASYOCR_DEFAULT_CONFIDENCE",
    default=0.3,
)
INFERENCE_MODELS_FLORENCE2_DEFAULT_MAX_NEW_TOKENS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_FLORENCE2_DEFAULT_MAX_NEW_TOKENS",
    default=INFERENCE_MODELS_DEFAULT_MAX_NEW_TOKENS,
)
INFERENCE_MODELS_FLORENCE2_DEFAULT_NUM_BEAMS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_FLORENCE2_DEFAULT_NUM_BEAMS",
    default=INFERENCE_MODELS_DEFAULT_NUM_BEAMS,
)
INFERENCE_MODELS_FLORENCE2_DEFAULT_DO_SAMPLE = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_FLORENCE2_DEFAULT_DO_SAMPLE",
    default=INFERENCE_MODELS_DEFAULT_DO_SAMPLE,
)
INFERENCE_MODELS_GROUNDING_DINO_DEFAULT_BOX_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_GROUNDING_DINO_DEFAULT_BOX_CONFIDENCE",
    default=0.5,
)
INFERENCE_MODELS_GROUNDING_DINO_DEFAULT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_GROUNDING_DINO_DEFAULT_MAX_DETECTIONS",
    default=INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS,
)
INFERENCE_MODELS_GROUNDING_DINO_DEFAULT_IOU_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_GROUNDING_DINO_DEFAULT_IOU_THRESHOLD",
    default=0.5,
)
INFERENCE_MODELS_MEDIAPIPE_FACE_DETECTOR_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_MEDIAPIPE_FACE_DETECTOR_DEFAULT_CONFIDENCE",
    default=0.5,
)
INFERENCE_MODELS_MOONDREAM2_DEFAULT_MAX_NEW_TOKENS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_MOONDREAM2_DEFAULT_MAX_NEW_TOKENS",
    default=700,
)
INFERENCE_MODELS_OWLV2_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_OWLV2_DEFAULT_CONFIDENCE",
    default=0.99,
)
INFERENCE_MODELS_OWLV2_DEFAULT_IOU_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_OWLV2_DEFAULT_IOU_THRESHOLD",
    default=INFERENCE_MODELS_DEFAULT_IOU_THRESHOLD,
)
INFERENCE_MODELS_OWLV2_DEFAULT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_OWLV2_DEFAULT_MAX_DETECTIONS",
    default=INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS,
)
INFERENCE_MODELS_OWLV2_DEFAULT_CLASS_AGNOSTIC_NMS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_OWLV2_DEFAULT_CLASS_AGNOSTIC_NMS",
    default=INFERENCE_MODELS_DEFAULT_CLASS_AGNOSTIC_NMS,
)
INFERENCE_MODELS_PALIGEMMA_DEFAULT_MAX_NEW_TOKENS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_PALIGEMMA_DEFAULT_MAX_NEW_TOKENS",
    default=400,
)
INFERENCE_MODELS_PALIGEMMA_DEFAULT_DO_SAMPLE = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_PALIGEMMA_DEFAULT_DO_SAMPLE",
    default=INFERENCE_MODELS_DEFAULT_DO_SAMPLE,
)
INFERENCE_MODELS_PALIGEMMA_DEFAULT_SKIP_SPECIAL_TOKENS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_PALIGEMMA_DEFAULT_SKIP_SPECIAL_TOKENS",
    default=True,
)
INFERENCE_MODELS_QWEN3_VL_DEFAULT_MAX_NEW_TOKENS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_QWEN3_VL_DEFAULT_MAX_NEW_TOKENS",
    default=512,
)
INFERENCE_MODELS_QWEN3_VL_DEFAULT_DO_SAMPLE = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_QWEN3_VL_DEFAULT_DO_SAMPLE",
    default=INFERENCE_MODELS_DEFAULT_DO_SAMPLE,
)
INFERENCE_MODELS_QWEN25_VL_DEFAULT_MAX_NEW_TOKENS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_QWEN25_VL_DEFAULT_MAX_NEW_TOKENS",
    default=512,
)
INFERENCE_MODELS_QWEN25_VL_DEFAULT_DO_SAMPLE = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_QWEN25_VL_DEFAULT_DO_SAMPLE",
    default=INFERENCE_MODELS_DEFAULT_DO_SAMPLE,
)
INFERENCE_MODELS_QWEN25_VL_DEFAULT_SKIP_SPECIAL_TOKENS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_QWEN25_VL_DEFAULT_SKIP_SPECIAL_TOKENS",
    default=True,
)
INFERENCE_MODELS_RESNET_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_RESNET_DEFAULT_CONFIDENCE",
    default=INFERENCE_MODELS_DEFAULT_CONFIDENCE,
)
INFERENCE_MODELS_RFDETR_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_RFDETR_DEFAULT_CONFIDENCE",
    default=INFERENCE_MODELS_DEFAULT_CONFIDENCE,
)
INFERENCE_MODELS_ROBOFLOW_INSTANT_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_ROBOFLOW_INSTANT_DEFAULT_CONFIDENCE",
    default=0.99,
)
INFERENCE_MODELS_ROBOFLOW_INSTANT_DEFAULT_IOU_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_ROBOFLOW_INSTANT_DEFAULT_IOU_THRESHOLD",
    default=0.3,
)
INFERENCE_MODELS_ROBOFLOW_INSTANT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_ROBOFLOW_INSTANT_MAX_DETECTIONS",
    default=INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS,
)
INFERENCE_MODELS_SMOL_VLM_DEFAULT_MAX_NEW_TOKENS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_SMOL_VLM_DEFAULT_MAX_NEW_TOKENS",
    default=400,
)
INFERENCE_MODELS_SMOL_VLM_DEFAULT_DO_SAMPLE = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_SMOL_VLM_DEFAULT_DO_SAMPLE",
    default=INFERENCE_MODELS_DEFAULT_DO_SAMPLE,
)
INFERENCE_MODELS_SMOL_VLM_DEFAULT_SKIP_SPECIAL_TOKENS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_SMOL_VLM_DEFAULT_SKIP_SPECIAL_TOKENS",
    default=True,
)
INFERENCE_MODELS_VIT_CLASSIFIER_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_VIT_CLASSIFIER_DEFAULT_CONFIDENCE",
    default=INFERENCE_MODELS_DEFAULT_CONFIDENCE,
)
INFERENCE_MODELS_YOLACT_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLACT_DEFAULT_CONFIDENCE",
    default=INFERENCE_MODELS_DEFAULT_CONFIDENCE,
)
INFERENCE_MODELS_YOLACT_DEFAULT_IOU_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLACT_DEFAULT_IOU_THRESHOLD",
    default=INFERENCE_MODELS_DEFAULT_IOU_THRESHOLD,
)
INFERENCE_MODELS_YOLACT_DEFAULT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_YOLACT_DEFAULT_MAX_DETECTIONS",
    default=INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS,
)
INFERENCE_MODELS_YOLACT_DEFAULT_CLASS_AGNOSTIC_NMS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_YOLACT_DEFAULT_CLASS_AGNOSTIC_NMS",
    default=INFERENCE_MODELS_DEFAULT_CLASS_AGNOSTIC_NMS,
)
INFERENCE_MODELS_YOLONAS_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLONAS_DEFAULT_CONFIDENCE",
    default=INFERENCE_MODELS_DEFAULT_CONFIDENCE,
)
INFERENCE_MODELS_YOLONAS_DEFAULT_IOU_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLONAS_DEFAULT_IOU_THRESHOLD",
    default=INFERENCE_MODELS_DEFAULT_IOU_THRESHOLD,
)
INFERENCE_MODELS_YOLONAS_DEFAULT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_YOLONAS_DEFAULT_MAX_DETECTIONS",
    default=INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS,
)
INFERENCE_MODELS_YOLONAS_DEFAULT_CLASS_AGNOSTIC_NMS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_YOLONAS_DEFAULT_CLASS_AGNOSTIC_NMS",
    default=INFERENCE_MODELS_DEFAULT_CLASS_AGNOSTIC_NMS,
)
INFERENCE_MODELS_YOLOV5_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLOV5_DEFAULT_CONFIDENCE",
    default=INFERENCE_MODELS_DEFAULT_CONFIDENCE,
)
INFERENCE_MODELS_YOLOV5_DEFAULT_IOU_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLOV5_DEFAULT_IOU_THRESHOLD",
    default=INFERENCE_MODELS_DEFAULT_IOU_THRESHOLD,
)
INFERENCE_MODELS_YOLOV5_DEFAULT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_YOLOV5_DEFAULT_MAX_DETECTIONS",
    default=INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS,
)
INFERENCE_MODELS_YOLOV5_DEFAULT_CLASS_AGNOSTIC_NMS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_YOLOV5_DEFAULT_CLASS_AGNOSTIC_NMS",
    default=INFERENCE_MODELS_DEFAULT_CLASS_AGNOSTIC_NMS,
)
INFERENCE_MODELS_YOLOV7_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLOV7_DEFAULT_CONFIDENCE",
    default=INFERENCE_MODELS_DEFAULT_CONFIDENCE,
)
INFERENCE_MODELS_YOLOV7_DEFAULT_IOU_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLOV7_DEFAULT_IOU_THRESHOLD",
    default=INFERENCE_MODELS_DEFAULT_IOU_THRESHOLD,
)
INFERENCE_MODELS_YOLOV7_DEFAULT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_YOLOV7_DEFAULT_MAX_DETECTIONS",
    default=INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS,
)
INFERENCE_MODELS_YOLOV7_DEFAULT_CLASS_AGNOSTIC_NMS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_YOLOV7_DEFAULT_CLASS_AGNOSTIC_NMS",
    default=INFERENCE_MODELS_DEFAULT_CLASS_AGNOSTIC_NMS,
)
INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_CONFIDENCE",
    default=INFERENCE_MODELS_DEFAULT_CONFIDENCE,
)
INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_IOU_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_IOU_THRESHOLD",
    default=INFERENCE_MODELS_DEFAULT_IOU_THRESHOLD,
)
INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_MAX_DETECTIONS",
    default=INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS,
)
INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_CLASS_AGNOSTIC_NMS = get_boolean_from_env(
    variable_name="INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_CLASS_AGNOSTIC_NMS",
    default=INFERENCE_MODELS_DEFAULT_CLASS_AGNOSTIC_NMS,
)
INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_KEY_POINTS_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLO_ULTRALYTICS_DEFAULT_KEY_POINTS_THRESHOLD",
    default=0.0,
)
INFERENCE_MODELS_YOLOV10_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLOV10_DEFAULT_CONFIDENCE",
    default=INFERENCE_MODELS_DEFAULT_CONFIDENCE,
)
INFERENCE_MODELS_YOLOV10_DEFAULT_MAX_DETECTIONS = get_integer_from_env(
    variable_name="INFERENCE_MODELS_YOLOV10_DEFAULT_MAX_DETECTIONS",
    default=INFERENCE_MODELS_DEFAULT_MAX_DETECTIONS,
)
INFERENCE_MODELS_YOLO26_DEFAULT_CONFIDENCE = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLO26_DEFAULT_CONFIDENCE",
    default=0.25,
)
INFERENCE_MODELS_YOLO26_DEFAULT_KEY_POINTS_THRESHOLD = get_float_from_env(
    variable_name="INFERENCE_MODELS_YOLO26_DEFAULT_KEY_POINTS_THRESHOLD",
    default=0.3,
)
