from typing import Any, List


class ModelManager:

    def load(self, model_id: str, api_key: str, **kwargs) -> None: ...

    def unload(self, model_id: str, api_key: str) -> None: ...

    def clear(self) -> None: ...

    async def infer_async(self, model_id: str, *args, **kwargs) -> Any: ...

    def infer_sync(self, model_id: str, *args, **kwargs) -> Any: ...

    def describe_models(self) -> List[Any]: ...

    def __contains__(self, model_id: str) -> bool: ...

    def __len__(self) -> int: ...
