defaults:
  - _self_

_target_: lidra.model.backbone.autoencoder.vae.create_autoencoder

# Model parameters (these will be passed to create_autoencoder)
depth: 12
dim: 768
M: 1024  # num_latents
latent_dim: 768
num_heads: 12
deterministic: false


# Additional parameters
drop_path_rate: 0.1
