defaults:
  - _self_

_target_: lidra.model.backbone.autoencoder.vae.create_autoencoder

# Model parameters (these will be passed to create_autoencoder)
depth: 24
dim: 512
M: 512 # num_latents
latent_dim: 32
num_heads: 8
deterministic: false

# Additional parameters
drop_path_rate: 0.1
