# @package _global_

cluster_path: /large_experiments/3dfy/model_weights
trellis_ckpts_dir: ${cluster_path}/TRELLIS-image-large/ckpts

inference_pipeline:
  _target_: lidra.pipeline.inference_pipeline_pointmap.InferencePipelinePointMap
  ss_generator_config_path: ${cluster_path}/v2_mot_shape_6drotation_normalized_inhouse_vae_ptmap_dropoutCFG_Feb-May-only/config.yaml
  ss_generator_ckpt_path: ${cluster_path}/v2_mot_shape_6drotation_normalized_inhouse_vae_ptmap_dropoutCFG_Feb-May-only/lightning/version_0/checkpoints/epoch=124-step=48000-v1.ckpt

  slat_generator_config_path: ${cluster_path}/fm-trellisDiT-features-ObjV1-ABO-ObjGithub-nvoxels15k-dinov2_vitl14_reg-518-16x8/config.yaml
  slat_generator_ckpt_path: ${trellis_ckpts_dir}/slat_flow_img_dit_L_64l8p2_fp16.safetensors

  ss_decoder_config_path: ${cluster_path}/ss_decoder/ss_decoder.yaml
  ss_decoder_ckpt_path: ${cluster_path}/ss_decoder/decoder.ckpt

  slat_decoder_gs_config_path: ${trellis_ckpts_dir}/slat_decoder_gs.yaml
  slat_decoder_gs_ckpt_path: ${trellis_ckpts_dir}/slat_dec_gs_swin8_B_64l8gs32_fp16.safetensors

  slat_decoder_mesh_config_path: ${trellis_ckpts_dir}/slat_decoder_mesh.yaml
  slat_decoder_mesh_ckpt_path: ${trellis_ckpts_dir}/slat_dec_mesh_swin8_B_64l8m256c_fp16.safetensors

  pad_size: 1.0
  dtype: float32
  version: v5
  ss_condition_input_mapping: []

  ss_preprocessor:
    _target_: lidra.data.dataset.tdfy.trellis.dataset.PreProcessor
    normalize_pointmap: true
    img_mask_joint_transform: []
    img_mask_pointmap_joint_transform:
      - _target_: lidra.data.dataset.tdfy.img_and_mask_transforms.resize_all_to_same_size
        _partial_: true
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_and_mask_transforms.crop_around_mask_with_padding
        box_size_factor: 1.2
        padding_factor: 0.0
    img_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        size: 518
    mask_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        interpolation: 0
        size: 518
    pointmap_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        interpolation: 0
        size: 518
  pose_decoder_name: ScaleShiftInvariant

  depth_model:
    _target_: lidra.pipeline.depth_models.moge.MoGe
    model:
      _target_: moge.model.v1.MoGeModel.from_pretrained
      pretrained_model_name_or_path: Ruicheng/moge-vitl