# @package _global_

cluster:
  path:
    weights: /fsx-3dfy-v2/shared/weights/
    config: /fsx-3dfy-v2/haotang/dev/lidra/etc/lidra/

inference_pipeline:
  _target_: lidra.pipeline.inference_pipeline_pointmap.InferencePipelinePointMap

  ss_generator_config_path: /fsx-3dfy-v3/ssax/3dfy/lidra/logs/tagged/_submit/${tdfy.layout_tag_name}/config.yaml
  ss_generator_ckpt_path: /fsx-3dfy-v3/ssax/3dfy/lidra/logs/tagged/_submit/${tdfy.layout_tag_name}/lightning/version_0/checkpoints/${tdfy.layout_model_ckpt_path}.ckpt
  
  
  ss_decoder_config_path: ${cluster.path.weights}/tdfy/TRELLIS-image-large/ckpts/ss_decoder.yaml
  ss_decoder_ckpt_path: ${cluster.path.weights}/tdfy/trellis-ss-vae-trial1-lambda1e-3-8x8/weiyao_decoder.ckpt

  slat_generator_config_path: /fsx-3dfy-v2/shared/weights/tdfy/TRELLIS-image-large/ckpts/fm-trellisDiT-features-ObjV1-ABO-ObjGithub-nvoxels15k-dinov2_vitl14_reg-518-16x8/config.yaml
  slat_generator_ckpt_path: ${cluster.path.weights}/tdfy/TRELLIS-image-large/ckpts/slat_flow_img_dit_L_64l8p2_fp16.safetensors

  slat_decoder_gs_config_path: ${cluster.path.weights}/tdfy/TRELLIS-image-large/ckpts/slat_decoder_gs_tdfyoptions.yaml
  slat_decoder_gs_ckpt_path: ${cluster.path.weights}/tdfy/TRELLIS-image-large/ckpts/slat_dec_gs_swin8_B_64l8gs32_fp16.safetensors
  slat_decoder_mesh_config_path: ${cluster.path.weights}/tdfy/TRELLIS-image-large/ckpts/slat_decoder_mesh_tdfyoptions.yaml
  slat_decoder_mesh_ckpt_path: ${cluster.path.weights}/tdfy/TRELLIS-image-large/ckpts/slat_dec_mesh_swin8_B_64l8m256c_fp16.safetensors

  pad_size: 1.0
  dtype: bfloat16
  version: 3dfy_v3

  device: ${tdfy.device}
  depth_model:
    _target_: lidra.pipeline.depth_models.moge.MoGe
    model:
      _target_: moge.model.v1.MoGeModel.from_pretrained
      pretrained_model_name_or_path: Ruicheng/moge-vitl
    device: ${tdfy.device}

  ss_condition_input_mapping: []  
  ss_preprocessor: null
  
  pose_decoder_name: null #ScaleShiftInvariant
  use_layout_result: false
  force_shape_in_layout: false
  decode_formats: ["gaussian"]

tdfy:
  device: cuda
  layout_tag_name: pointmap_norm-procthor-pmNormDisparityObj
  layout_model_ckpt_path: last 