# @package _global_

cluster_path: /checkpoint/3dfy/
trellis_ckpts_dir: ${cluster_path}/haotang/dev/TRELLIS-image-large/ckpts
config_dir: ${cluster_path}/haotang/dev/lidra/etc/lidra/
lidra_ckpt_dir: ${cluster_path}/weiyaowang/lidra 

inference_pipeline:
  _target_: lidra.pipeline.inference_pipeline.InferencePipeline
  ss_generator_config_path: ${lidra_ckpt_dir}/logs/tagged/_submit/fm-force_zeros_cond-trellis500k-rPad.2_colorAug-16x8/config.yaml
  ss_generator_ckpt_path: ${lidra_ckpt_dir}/logs/tagged/_submit/fm-force_zeros_cond-trellis500k-rPad.2_colorAug-16x8/lightning/version_0/checkpoints/last.ckpt
  slat_generator_config_path: ${lidra_ckpt_dir}/logs/tagged/_submit/fm-trellisDiT-features-ObjV1-ABO-ObjGithub-nvoxels15k-dinov2_vitl14_reg-518-16x8/config.yaml
  slat_generator_ckpt_path: ${trellis_ckpts_dir}/slat_flow_img_dit_L_64l8p2_fp16.safetensors
  ss_decoder_config_path: ${config_dir}/model/backbone/trellis_vae/ss_decoder.yaml
  ss_decoder_ckpt_path: ${trellis_ckpts_dir}/ss_dec_conv3d_16l8_fp16.safetensors
  slat_decoder_gs_config_path: ${config_dir}/model/backbone/trellis_vae/slat_decoder_gs.yaml
  slat_decoder_gs_ckpt_path: ${trellis_ckpts_dir}/slat_dec_gs_swin8_B_64l8gs32_fp16.safetensors
  slat_decoder_mesh_config_path: ${config_dir}/model/backbone/trellis_vae/slat_decoder_mesh.yaml
  slat_decoder_mesh_ckpt_path: ${trellis_ckpts_dir}/slat_dec_mesh_swin8_B_64l8m256c_fp16.safetensors
  
  pad_size: 1.0
  dtype: float32
  version: v0