# @package _global_

cluster_path: /checkpoint/3dfy/
trellis_ckpts_dir: /checkpoint/3dfy/shared/weights/tdfy/TRELLIS-image-large/ckpts
config_dir: ${cluster_path}/haotang/dev/lidra/etc/lidra/
lidra_ckpt_dir: ${cluster_path}/weiyaowang/lidra 

cluster:
  path:
    weights: /checkpoint/3dfy/shared/weights/

inference_pipeline:
  _target_: lidra.pipeline.inference_pipeline_pointmap.InferencePipelinePointMap
  ss_generator_config_path: /checkpoint/3dfy/haotang/lidra/logs/tagged/_submit/v2_mot_quaternion_layout_Feb-April/config.yaml
  ss_generator_ckpt_path: /checkpoint/3dfy/haotang/lidra/logs/tagged/_submit/v2_mot_quaternion_layout_Feb-April/lightning/version_0/checkpoints/last.ckpt
  slat_generator_config_path: ${lidra_ckpt_dir}/logs/tagged/_submit/fm-trellisDiT-features-ObjV1-ABO-ObjGithub-nvoxels15k-dinov2_vitl14_reg-518-16x8/config.yaml
  slat_generator_ckpt_path: ${trellis_ckpts_dir}/slat_flow_img_dit_L_64l8p2_fp16.safetensors
  ss_decoder_config_path: ${config_dir}/model/backbone/trellis_vae/ss_decoder.yaml
  ss_decoder_ckpt_path: ${trellis_ckpts_dir}/ss_dec_conv3d_16l8_fp16.safetensors
  slat_decoder_gs_config_path: ${config_dir}/model/backbone/trellis_vae/slat_decoder_gs.yaml
  slat_decoder_gs_ckpt_path: ${trellis_ckpts_dir}/slat_dec_gs_swin8_B_64l8gs32_fp16.safetensors
  slat_decoder_mesh_config_path: ${config_dir}/model/backbone/trellis_vae/slat_decoder_mesh.yaml
  slat_decoder_mesh_ckpt_path: ${trellis_ckpts_dir}/slat_dec_mesh_swin8_B_64l8m256c_fp16.safetensors

  layout_model_config_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/layoutv0-r3v0_2-eitr-ptmap-cropIsFullImgTransform/config.yaml
  layout_model_ckpt_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/layoutv0-r3v0_2-eitr-ptmap-cropIsFullImgTransform/lightning/version_0/checkpoints/last.ckpt

  pad_size: 1.0
  dtype: float16
  version: 3dfy_v3

  ss_condition_input_mapping: []  
  ss_preprocessor:
    _target_: lidra.data.dataset.tdfy.trellis.dataset.PreProcessor
    img_transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
          _partial_: true
        - _target_: torchvision.transforms.Resize
          size: 518
    mask_transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
          _partial_: true
        - _target_: torchvision.transforms.Resize
          size: 518
          interpolation: 0 # nearest
    img_mask_joint_transform:
      - _target_: lidra.data.dataset.tdfy.img_and_mask_transforms.crop_around_mask_with_padding
        _partial_: true
        box_size_factor: 1.2
        padding_factor: 0.0 

  layout_condition_input_mapping: []
  layout_preprocessor:
    _target_: lidra.data.dataset.tdfy.trellis.dataset.PreProcessor
    img_mask_joint_transform: []
    # - _partial_: true
    #   _target_: lidra.data.dataset.tdfy.img_and_mask_transforms.crop_around_mask_with_padding
    #   box_size_factor: 1.2
    #   padding_factor: 0.0
    img_mask_pointmap_joint_transform: []
    img_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        size: 518
    mask_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        interpolation: 0
        size: 518
    pointmap_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        interpolation: 0
        size: 518

  pose_decoder_name: ScaleShiftInvariant
  use_layout_result: true
  force_shape_in_layout: true
  decode_formats: ["gaussian"]