# @package _global_

cluster_path: /checkpoint/3dfy/
trellis_ckpts_dir: ${cluster_path}/haotang/dev/TRELLIS-image-large/ckpts
config_dir: /private/home/gleize/code/fair/lidra@3dfy/etc
lidra_ckpt_dir: /private/home/gleize/code/fair/lidra@3dfy/triton/tdfy/1/checkpoints

inference_pipeline:
  _target_: lidra.pipeline.inference_pipeline.InferencePipeline
  ss_generator_config_path: ${lidra_ckpt_dir}/ss_generator.yaml
  ss_generator_ckpt_path: ${lidra_ckpt_dir}/ss_generator.ckpt
  slat_generator_config_path: ${lidra_ckpt_dir}/slat_generator.yaml
  slat_generator_ckpt_path: ${lidra_ckpt_dir}/slat_generator.safetensors
  ss_decoder_config_path: ${lidra_ckpt_dir}/ss_decoder.yaml
  ss_decoder_ckpt_path: ${lidra_ckpt_dir}/ss_decoder.safetensors
  slat_decoder_gs_config_path: ${lidra_ckpt_dir}/slat_decoder_gs.yaml
  slat_decoder_gs_ckpt_path: ${lidra_ckpt_dir}/slat_decoder_gs.safetensors
  slat_decoder_mesh_config_path: ${lidra_ckpt_dir}/slat_decoder_mesh.yaml
  slat_decoder_mesh_ckpt_path: ${lidra_ckpt_dir}/slat_decoder_mesh.safetensors

  pad_size: 1.0
  dtype: float32
  version: v0
