FROM nvcr.io/nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04 as base
#has python 3.10

WORKDIR /app

RUN rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libxext6 \
    libopencv-dev \
    uvicorn \
    python3-pip \
    git \
    libgdal-dev \
    rustc \
    cargo \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/requirements.http.txt \
    requirements/requirements.gpu.txt \
    requirements/_requirements.txt \
    requirements/requirements.cli.txt \
    requirements/requirements.sdk.http.txt \
    ./

RUN pip3 install --upgrade pip  && pip3 install \
    -r _requirements.txt \
    -r requirements.http.txt \
    -r requirements.gpu.txt \
    -r requirements.cli.txt \
    -r requirements.sdk.http.txt \
    "setuptools<=75.5.0" \
    --upgrade \
    && rm -rf ~/.cache/pip

FROM scratch
COPY --from=base / /

WORKDIR /app/
COPY inference inference
COPY inference_sdk inference_sdk
COPY inference_cli inference_cli
ENV PYTHONPATH=/app/


COPY docker/config/gpu_http.py gpu_http.py

ENV CORE_MODEL_CLIP_ENABLED=false
ENV CORE_MODEL_PE_ENABLED=false
ENV CORE_MODEL_SAM_ENABLED=false
ENV CORE_MODEL_GAZE_ENABLED=false
ENV CORE_MODEL_DOCTR_ENABLED=false
ENV VERSION_CHECK_MODE=continuous
ENV PROJECT=roboflow-platform
ENV NUM_WORKERS=1
ENV HOST=0.0.0.0
ENV PORT=9001
ENV WORKFLOWS_STEP_EXECUTION_MODE=local
ENV WORKFLOWS_MAX_CONCURRENT_STEPS=4
ENV API_LOGGING_ENABLED=True
ENV CORE_MODEL_TROCR_ENABLED=false
ENV ENABLE_PROMETHEUS=True
ENV CORE_MODEL_EASYOCR_ENABLED=False
ENTRYPOINT uvicorn gpu_http:app --workers $NUM_WORKERS --host $HOST --port $PORT