FROM python:3.11-bookworm as base

ARG DEBIAN_FRONTEND=noninteractive
ARG TARGETPLATFORM

RUN apt update -y && apt install -y \
    libxext6 \
    libopencv-dev \
    uvicorn \
    python3-pip \
    git \
    libgdal-dev \
    cmake \
    rustc \
    cargo \
    && rm -rf /var/lib/apt/lists/*


COPY requirements/requirements.cpu.txt \
    requirements/requirements.http.txt \
    requirements/_requirements.txt \
    requirements/requirements.vino.txt \
    requirements/requirements.cli.txt \
    requirements/requirements.sdk.http.txt \
    requirements/requirements.modal.txt \
    ./

RUN if [ "${TARGETPLATFORM}" = "linux/amd64" ]; then mv requirements.vino.txt requirements.cpu.txt; fi

RUN pip3 install --upgrade pip && pip3 install "wheel>=0.38.1,<=0.45.1"
RUN pip3 install \
    -r _requirements.txt \
    -r requirements.cpu.txt \
    -r requirements.http.txt \
    -r requirements.cli.txt \
    -r requirements.sdk.http.txt \
    -r requirements.modal.txt \
    "setuptools<=75.5.0" \
    --upgrade \
    && rm -rf ~/.cache/pip

FROM scratch
COPY --from=base / /

WORKDIR /app

COPY inference inference
COPY inference_sdk inference_sdk
COPY inference_cli inference_cli
COPY docker/config/cpu_http.py cpu_http.py

ENV CORE_MODEL_CLIP_ENABLED=false
ENV CORE_MODEL_PE_ENABLED=false
ENV CORE_MODEL_SAM_ENABLED=false
ENV CORE_MODEL_GAZE_ENABLED=false
ENV CORE_MODEL_DOCTR_ENABLED=false
ENV CORE_MODEL_TROCR_ENABLED=false
ENV VERSION_CHECK_MODE=continuous
ENV PROJECT=roboflow-platform
ENV NUM_WORKERS=1
ENV HOST=0.0.0.0
ENV PORT=9001
ENV WORKFLOWS_STEP_EXECUTION_MODE=local
ENV WORKFLOWS_MAX_CONCURRENT_STEPS=4
ENV API_LOGGING_ENABLED=True
ENV ENABLE_PROMETHEUS=True
ENV CORE_MODEL_EASYOCR_ENABLED=False
ENV CORE_MODEL_SAM3_ENABLED=False

ENTRYPOINT uvicorn cpu_http:app --workers $NUM_WORKERS --host $HOST --port $PORT