FROM us-docker.pkg.dev/colab-images/public/runtime:latest

COPY . .
RUN pip uninstall -y torchaudio
RUN make create_wheels
RUN pip install --find-links dist/ dist/roboflow_workflows*.whl dist/inference_cpu*.whl
RUN pip install -r requirements/requirements.test.colab.txt

ENTRYPOINT ["pytest", "tests/google_colab/"]
