# @package _global_
defaults:
  - /run/train/tdfy@: base

  - /model/module/tdfy@module: generative
  - /model/backbone@module.generator: trainable
  - /model/backbone/generator@module.generator.backbone: ???
  - /optimizer@module.generator.optimizer: adam

  - override /loop: normal
  - override /hydra: slurm
  - override /strategy: auto
  - override /compute: 8x8

  - override /data/module@loop.dataloaders: ???

  - _self_

batch_size: 4
lr: 1e-4

loop:
  max_epochs: 100

module:
  generator:
    optimizer:
      lr: ${lr}
