# @package _global_
defaults:
  - ddpm-3d-features

  # dataset
  - override /data/module@loop.dataloaders: tdfy/objaverse-xcube

  - _self_

batch_size: 4

module:
  latent_scale_factor: 0.317 # from https://github.com/nv-tlabs/XCube/blob/254d95b2bca540c20aced686027055a9bff392ed/xcube/models/diffusion.py#L277

tdfy:
  reverse_fn:
    input_size: 8
    n_tokens: 4096
