# @package _global_
defaults:
  - base
  # - /model/backbone@module.generator.backbone.reverse_fn: dit/small
  - /model/backbone@module.generator.backbone.reverse_fn: unet/diffusion
  - override /model/backbone/generator@module.generator.backbone: ddim
  - override /data/module@loop.dataloaders: imagenet
  - _self_

batch_size: 16

module:
  batch_encoder_input_mapping: 0
  batch_decoder_input_mapping: ${rv.locate:lidra.data.utils.empty_mapping}
  batch_conditions_mapping: ${rv.locate:lidra.data.utils.empty_mapping}

  validation_dump_type: image
  ##< enable following when using DiT backbone
  # generator:
  #   backbone:
  #     reverse_fn:
  #       input_size: 128
  #       patch_size: 2
  #       input_channels: 3
  #       learn_sigma: false
  #       num_classes: null
  #       input_type: image
  #       condition_type: none
  ##

loop:
  limit_val_batches: 10

  dataloaders:
    training:
      dataset:
        transform: ${tdfy.transform}
    validation:
      dataset:
        transform: ${tdfy.transform}

tdfy:
  collator:
    _target_: lidra.data.collator.auto_collate

  transform:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToImage
      - _target_: torchvision.transforms.v2.Resize
        size: 128
      - _target_: torchvision.transforms.v2.CenterCrop
        size: 128
      - _target_: torchvision.transforms.v2.ToDtype
        dtype: ${rv.locate:torch.float32}
        scale: true
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
