# @package _global_
defaults:
  - base

  # generator
  - /model/backbone@tdfy.reverse_fn: dit/x-large

  - override /model/module/tdfy@module: generative-features-only
  - override /model/backbone/generator@module.generator.backbone: ddim

  - _self_

batch_size: 16

module:
  batch_conditions_mapping: "image" # rgb-image
  generator:
    backbone:
      reverse_fn: ${tdfy.reverse_fn} # no classifier-free guidance
      # reverse_fn:
      #   backbone: ${tdfy.reverse_fn} # with classifier-free guidance

loop:
  dataloaders:
    validation: null

tdfy:
  collator:
    _target_: lidra.data.collator.auto_collate

  reverse_fn:
    cond_image_size: 512
    learn_sigma: false
    input_type: "tokens+linear"
    condition_type: dino # dino (=conditional), none (=unconditional)
