"""Check that every redirect destination on inference.roboflow.com is reachable.

The documentation moved to docs.roboflow.com. This site is now a landing page
plus redirects, with destination URLs declared in three places:

* ``redirect_url`` front matter on the Markdown pages under ``docs/``
* the exact-match and prefix tables in the 404 router, ``theme/404.html``
* the landing page links in ``theme/home.html`` and the nav in ``mkdocs.yml``

This script collects every destination from those sources, requests each one,
and exits non-zero if any of them does not return 200. It also reports
destinations whose anchor is missing from the target page, which is a warning
rather than a failure because anchors are generated by the docs platform.

It is deliberately NOT wired into CI: it talks to the public internet and would
flake. Run it by hand after changing a redirect destination, or periodically to
catch pages that moved on docs.roboflow.com.

Usage:
    python -m development.docs.check_redirect_destinations
    python -m development.docs.check_redirect_destinations --timeout 20 --workers 16
"""

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DOCS_DIR = os.path.join(REPO_ROOT, "docs")
ROUTER_FILE = os.path.join(REPO_ROOT, "theme", "404.html")

USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/125.0 Safari/537.36"
)

FRONT_MATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
REDIRECT_URL_RE = re.compile(r"^redirect_url:\s*(\S+)\s*$", re.MULTILINE)
ROUTER_URL_RE = re.compile(r'"(https://docs\.roboflow\.com[^"]*)"')


def collect_front_matter_destinations() -> dict[str, str]:
    """Map each redirect page to the URL it points at."""
    destinations = {}
    for dirpath, _, filenames in os.walk(DOCS_DIR):
        for filename in filenames:
            if not filename.endswith(".md"):
                continue
            path = os.path.join(dirpath, filename)
            with open(path, encoding="utf-8") as handle:
                head = handle.read(2048)
            front_matter = FRONT_MATTER_RE.match(head)
            if not front_matter:
                continue
            match = REDIRECT_URL_RE.search(front_matter.group(1))
            if match:
                destinations[os.path.relpath(path, REPO_ROOT)] = match.group(1)
    return destinations


def collect_router_destinations() -> dict[str, str]:
    """Map each 404 router entry to the URL it points at."""
    with open(ROUTER_FILE, encoding="utf-8") as handle:
        source = handle.read()
    return {
        f"{os.path.relpath(ROUTER_FILE, REPO_ROOT)}#{index}": url
        for index, url in enumerate(sorted(set(ROUTER_URL_RE.findall(source))))
    }


def collect_landing_page_destinations() -> dict[str, str]:
    """Map each landing page and nav link to the URL it points at."""
    destinations = {}
    for relative in ("theme/home.html", "mkdocs.yml"):
        path = os.path.join(REPO_ROOT, relative)
        with open(path, encoding="utf-8") as handle:
            source = handle.read()
        for index, url in enumerate(sorted(set(ROUTER_URL_RE.findall(source)))):
            destinations[f"{relative}#{index}"] = url
    return destinations


def fetch(url: str, timeout: int) -> tuple[int, str]:
    """Return the status code and body for *url*, following redirects."""
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return response.status, response.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as error:
        return error.code, ""
    except Exception as error:  # noqa: BLE001 - network errors are reported, not raised
        print(f"  request failed for {url}: {error}", file=sys.stderr)
        return 0, ""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--timeout", type=int, default=30, help="per-request timeout in seconds")
    parser.add_argument("--workers", type=int, default=8, help="number of parallel requests")
    parser.add_argument("--json", action="store_true", help="print results as JSON")
    args = parser.parse_args()

    sources = collect_front_matter_destinations()
    sources.update(collect_router_destinations())
    sources.update(collect_landing_page_destinations())
    if not sources:
        print("No redirect destinations found.", file=sys.stderr)
        return 1

    # Several pages share a destination, and anchors point at the same page.
    pages = sorted({url.split("#", 1)[0] for url in sources.values()})
    print(f"Found {len(sources)} redirect declarations -> {len(pages)} unique pages.")

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        results = dict(zip(pages, pool.map(lambda url: fetch(url, args.timeout), pages)))

    failures = []
    for declaration, url in sorted(sources.items()):
        page = url.split("#", 1)[0]
        status, _ = results[page]
        if status != 200:
            failures.append((declaration, url, status))

    missing_anchors = []
    for declaration, url in sorted(sources.items()):
        if "#" not in url:
            continue
        page, anchor = url.split("#", 1)
        status, body = results[page]
        if status == 200 and f'"{anchor}"' not in body:
            missing_anchors.append((declaration, url))

    if args.json:
        print(json.dumps(
            {
                "checked": len(sources),
                "pages": len(pages),
                "failures": [{"source": s, "url": u, "status": c} for s, u, c in failures],
                "missing_anchors": [{"source": s, "url": u} for s, u in missing_anchors],
            },
            indent=2,
        ))
    else:
        for declaration, url in missing_anchors:
            print(f"WARNING anchor not found: {declaration} -> {url}")
        for declaration, url, status in failures:
            print(f"FAIL {status or 'ERR'}: {declaration} -> {url}")
        ok = len(pages) - len({u.split("#", 1)[0] for _, u, _ in failures})
        print(f"\n{ok}/{len(pages)} pages returned 200.")
        print(f"{len(missing_anchors)} anchors could not be found (warning only).")

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
