# @package _global_

cluster_path: /checkpoint/3dfy/
trellis_ckpts_dir: /checkpoint/3dfy/shared/weights/tdfy/TRELLIS-image-large/ckpts
lidra_ckpt_dir: ${cluster_path}/weiyaowang/lidra 

cluster:
  path:
    weights: /checkpoint/3dfy/shared/weights/

inference_pipeline:
  _target_: lidra.pipeline.inference_pipeline_pointmap.InferencePipelinePointMap
  ss_generator_config_path: /checkpoint/3dfy/haotang/lidra/logs/tagged/_submit/v0-tricks-moge-mm-ft-artist-3D-0725/config.yaml
  ss_generator_ckpt_path: /checkpoint/3dfy/haotang/lidra/logs/tagged/_submit/v0-tricks-moge-mm-ft-artist-3D-0725/lightning/version_0/checkpoints/last.ckpt
  ss_decoder_config_path: ${trellis_ckpts_dir}/ss_decoder_demo.yaml
  ss_decoder_ckpt_path: ${trellis_ckpts_dir}/ss_dec_conv3d_16l8_fp16.safetensors
  
  slat_decoder_gs_config_path: /checkpoint/3dfy/shared/weights/tdfy/slat-vae-training-gsplat/slat_decoder_gs.yaml
  slat_decoder_gs_ckpt_path: /checkpoint/3dfy/shared/weights/tdfy/slat-vae-training-gsplat/slat_gs_decoder_epoch249.ckpt
  
  # mesh Decoder currently not used for visualizations
  slat_decoder_mesh_config_path: ${trellis_ckpts_dir}/slat_decoder_mesh.yaml
  slat_decoder_mesh_ckpt_path: ${trellis_ckpts_dir}/slat_dec_mesh_swin8_B_64l8m256c_fp16.safetensors
  # slat_decoder_mesh_ckpt_path: /checkpoint/3dfy/weiyaowang/trellis/logs/trellis-train-mesh-inhouseGSPLAT-12x8/ckpts/decoder_ema0.9999_step0085000.pt

  layout_model_config_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/layoutv0-r3v0_2-eitr-ptmap-cfg/config.yaml
  layout_model_ckpt_path: /checkpoint/3dfy/ssax/lidra/logs/tagged/_submit/layoutv0-r3v0_2-eitr-ptmap-cfg/lightning/version_0/checkpoints/last.ckpt
  use_layout_result: true
  force_shape_in_layout: true

  depth_model:
    _target_: lidra.pipeline.depth_models.moge.MoGe
    model:
      _target_: moge.model.v1.MoGeModel.from_pretrained
      pretrained_model_name_or_path: Ruicheng/moge-vitl

  layout_condition_input_mapping: []
  layout_preprocessor:
    _target_: lidra.data.dataset.tdfy.trellis.dataset.PreProcessor
    img_mask_joint_transform: []
    img_mask_pointmap_joint_transform: 
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_and_mask_transforms.crop_around_mask_with_padding
        box_size_factor: 1.2
        padding_factor: 0.0
    img_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        size: 518
    mask_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        interpolation: 0
        size: 518
    pointmap_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        interpolation: 0
        size: 518

  pad_size: 1.0
  dtype: float16
  version: 3dfy_v4_pm_pretrain_inhouseGSPLAT

  ss_condition_input_mapping: []  

  pose_decoder_name: ScaleShiftInvariant
  decode_formats: ["gaussian"]

  use_pretrained_slat: false
  slat_generator_config_path: /checkpoint/3dfy/shared/weights/tdfy/WEIYAO_fm-trellis-features-trellis500k-tricksNew-inHouseVAE-stk3d3-16x8-torchSparse/config_converted.yaml
  slat_generator_ckpt_path: /checkpoint/3dfy/shared/weights/tdfy/WEIYAO_fm-trellis-features-trellis500k-tricksNew-inHouseVAE-stk3d3-16x8-torchSparse/lightning/version_0/checkpoints/last_converted_spconv.ckpt
  rendering_engine: gsplat