# @package _global_
# Base configuration for v3 comparison analysis with direct instantiation
defaults:
  - ../base
  - _self_

# Processor instantiation
processor:
  _target_: lidra.metrics.analysis.v3.processor.analysis_comparison.AnalysisComparisonProcessor

# Config instantiation
config:
  _target_: lidra.metrics.analysis.v3.processor.analysis_comparison.AnalysisComparisonConfig
  
  # Core inputs
  experiments: ???  # Must be specified
  experiment_names: null
  
  # Analysis settings
  analysis_config: stage1
  overwrites: {}
  
  # Comparison settings
  statistic: mean
  
  # Execution
  parallel_analyses: false
  max_workers: 4
  
  # Display options
  metrics_filter: null
  sort_by: null
  ascending: true
  transpose: false
  show_missing_as: "N/A"