_target_: lidra.model.backbone.trellis.models.mm_latent.Latent
in_channels: 4
model_channels: ???
pos_embedder:
  _target_: lidra.model.backbone.trellis.models.mm_latent.LearntPositionEmbedder
  model_channels: ???
  # default 1 token with feature channel = 8
  token_len: 1