_target_: lidra.model.backbone.mcc.model.MCC
encoder_embed_dim: 768
encoder_n_blocks: 12
encoder_n_heads: 12
encoder_n_cls_tokens: 1
decoder_embed_dim: 512
decoder_n_blocks: 8
decoder_n_heads: 16
mlp_ratio: 4
drop_path: 0.1
max_n_queries: 200000
color_prediction: true
