# @package _global_
defaults:
  - /run/inference/tdfy/base
  - /data/module@loop.dataloaders: tdfy/with_cached_prediction
  - /loop/callbacks@callbacks.compute_metrics: metrics_tdfy
  - /model/module@module: tdfy/passthrough
  - _self_


prediction_folder: ???

# Load original samples corresponding to cached predictions
dataset_node_in_config: loop.dataloaders.validation.dataset
sample_dataset: ${rv.merge:${rv.config_node:${prediction_folder}/config.yaml, ${dataset_node_in_config}},${overwrites.sample_dataset}}

logs:
  path: ${rv.config_node:${prediction_folder}/config.yaml, logs.path}

module:
  _target_: lidra.model.module.tdfy.passthrough.Passthrough

loop:
  module: ${module}
  enable_progress_bar: true

  # Swap in the dataset with cached predictions
  dataloaders:
    validation:
      batch_size: ${batch_size}
      collate_fn:
        _target_: lidra.data.collator.auto_collate
      dataset:
        _target_: lidra.data.dataset.tdfy.with_cached_predictions_dataset.WithCachedPredictionDataset
        sample_dataset: ${sample_dataset}
        prediction_folder: ${prediction_folder}/cached_predictions

tdfy: ${rv.merge:${logs.config.tdfy},${overwrites.tdfy}}

overwrites:
  tdfy: null
  sample_dataset: null

predict:
  args:
    dataloader: ${loop.dataloaders.validation}

# Allow running on dev partition in H200
cluster:
  slurm:
    timeout: 1440 # 1440 minutes = 24 hours