# @package _global_
defaults:
  - /run/inference/tdfy/metrics/cached_predictions/base
  
  - /model/backbone@module.backbone: frozen
  - /model/backbone@module.backbone.backbone: trellis_vae/ss_decoder
  - _self_

callbacks:
  compute_metrics:

    batch_preprocess_fn:
      _target_: lidra.callback.tdfy.compute_metrics.batch_preprocess_fn_for_cached_predictions
      _partial_: true
      batch_key: "mean"
      output_key: ${metrics_mapping.shape_output_key}
      remaining_key_mapping: 
        scene_scale: "pointmap_scale"
        scene_shift: "pointmap_shift"
        instance_scale_l2c: "instance_scale_l2c"
        instance_position_l2c: "instance_position_l2c"
        instance_quaternion_l2c: "instance_quaternion_l2c"
      module_extractor_str: ${metrics_mapping.module_extractor_str}
    sample_extractor_fn: ${rv.locate:lidra.data.utils.kwargs_identity_mapping}
    
    prediction_preprocess_fn:
      _target_: lidra.callback.tdfy.compute_metrics.coords_prediction_preprocess_fn
      batch_key: "coords"
      output_key: ${metrics_mapping.shape_output_key}
      _partial_: true
      # _target_: lidra.callback.tdfy.compute_metrics.inference_pipeline_prediction_preprocess_fn
      # batch_key: "x_shape_latent"
      # output_key: ${metrics_mapping.shape_output_key}
      # module_extractor_str: ${metrics_mapping.module_extractor_str}
      # _partial_: true
    prediction_extractor_fn: ${rv.locate:lidra.data.utils.kwargs_identity_mapping}

module:
  batch_preprocessing_fn:
    _target_: lidra.callback.tdfy.compute_metrics.extract_trial_prediction_from_inference_pipeline
    _partial_: true
    pose_convention: "Identity"  # Inference pipeline outputs in the "standard" pose convention
    # Can optionally override key_mapping, dimension_adjustments, passthrough_keys here
  batch_input_mapping: ${rv.locate:lidra.data.utils.kwargs_identity_mapping}
 
  backbone:
    backbone:
      reshape_input_to_cube: true

        
metrics_mapping:
  module_extractor_str: "_base_models.backbone"
  shape_output_key: "occupancy_volume"

# Override logs path for inference pipeline outputs
logs:
  path: ${rv.config_node_resolved:${prediction_folder}/config.yaml, cluster.path.logs}
  config: ${rv.config_resolved:${prediction_folder}/config.yaml}

hydra:
  job:
    name: ${oc.select:tag.name,test}