# @package _global_
defaults:
  - /run/inference/tdfy/metrics/cached_predictions/base
  
  - /model/backbone@module.backbone: frozen
  - /model/backbone@module.backbone.backbone: trellis_vae/ss_decoder
  - _self_

callbacks:
  compute_metrics:

    batch_preprocess_fn:
      _target_: lidra.callback.tdfy.compute_metrics.batch_preprocess_fn_for_cached_predictions
      batch_key: "mean"
      output_key: ${metrics_mapping.shape_output_key}
      remaining_key_mapping: ${metrics_mapping.batch_remaining_key_mapping}
      module_extractor_str: ${metrics_mapping.module_extractor_str}
      _partial_: true
    sample_extractor_fn: ${rv.locate:lidra.data.utils.kwargs_identity_mapping}
    
    prediction_preprocess_fn:
      _target_: lidra.callback.tdfy.compute_metrics.TdfySingleTrialMetricsCallback.decode_shape_latents_and_passthrough_keys
      batch_key: "x_shape_latent"
      output_key: ${metrics_mapping.shape_output_key}
      module_extractor_str: ${metrics_mapping.module_extractor_str}
      _partial_: true
    prediction_extractor_fn: ${rv.locate:lidra.data.utils.kwargs_identity_mapping}

module:
  batch_preprocessing_fn:
    _target_:  lidra.callback.tdfy.compute_metrics.extract_trial_prediction_from_cached_prediction
    _partial_: true
  batch_input_mapping: ${metrics_mapping.prediction_passthrough_mapping}
 
  backbone:
    backbone:
      reshape_input_to_cube: true



metrics_mapping:
  module_extractor_str: "_base_models.backbone"
  shape_output_key: "occupancy_volume"

  prediction_passthrough_mapping:
    trial_idx: "trial_idx"
    x_shape_latent: "x_shape_latent"

  batch_remaining_key_mapping: {}