# @package _global_
defaults:
  - /run/inference/tdfy/metrics/cached_predictions/base
  - /model/backbone@module.backbone: frozen
  - /model/backbone@module.backbone.backbone: trellis_vae/ss_decoder
  - _self_
  - override /loop/callbacks@callbacks.compute_metrics: vlm_metrics_tdfy

callbacks:
  compute_metrics:
    batch_preprocess_fn:
      _target_: lidra.callback.tdfy.compute_vlm_metrics.batch_preprocess_fn_for_vlm_scoring
      remaining_key_mapping: ${metrics_mapping.vlm_preprocess_mapping}
      _partial_: true
    sample_extractor_fn: ${metrics_mapping.vlm_passthrough_mapping}
    prediction_extractor_fn: ${metrics_mapping.prediction_passthrough_mapping}
    evaluation_fn:
      _target_: lidra.callback.tdfy.compute_vlm_metrics.TdfySingleTrialVLMMetricsCallback.em_vlm_evaluation_fn
    scorer:
      _target_: lidra.metrics.tdfy.vlmscore.GPTScorer
      model_name: "4O"
      prompt_path: "${hydra:runtime.cwd}/etc/lidra/run/inference/tdfy/metrics/cached_predictions/vlm_configs/scoring_prompt.md"
      icl_config_path: "${hydra:runtime.cwd}/etc/lidra/run/inference/tdfy/metrics/cached_predictions/vlm_configs/icl_scoring.yaml"
      model_config_path: "${hydra:runtime.cwd}/etc/lidra/run/inference/tdfy/metrics/cached_predictions/vlm_configs/model.yaml"
      icl_img_root: "/fsx-3dfy-v2/ziqima/data/icl"


module:
  batch_preprocessing_fn: ${rv.locate:lidra.data.dataset.return_type.extract_data}
  batch_input_mapping: ${metrics_mapping.prediction_passthrough_mapping}
 
  backbone:
    backbone:
      reshape_input_to_cube: true



metrics_mapping:
  module_extractor_str: "_base_models.backbone"
  shape_output_key: "occupancy_volume"

  vlm_preprocess_mapping:
    input_cropped: "img_cropped_rgb"
    rendered: "rendered_multiview_img"

  vlm_passthrough_mapping:
    trial_idx: "trial_idx"
    input_full_highlighted: "input_full_highlighted"
    input_cropped_highlighted: "input_cropped_highlighted"
    input_cropped: "input_cropped"
    rendered: "rendered"

  prediction_passthrough_mapping:
    trial_idx: "trial_idx"

  batch_remaining_key_mapping: {}
