# @package _global_
defaults:
  - ../fm-trellis-trellis500k

  # load pretrained backbone
  - /data/dataset/tdfy/trellis500k/preprocessor@tdfy.preprocessor: train_keep_bg

  - override /model/backbone@tdfy.reverse_fn: trellis_dit/image_large_pretrained
  - override /model/backbone/dit/embedder@tdfy.reverse_fn.model.condition_embedder: image_mask_dino_dino
  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_fo_v1
  
lr: 1e-4  

module:
  batch_conditions_mapping: ["image", "mask"] # cropped image, cropped mask
  generator:
    backbone:
      reverse_fn:
        unconditional_handling: "add_flag"

loop:
  max_epochs: 100
  dataloaders:
    validation: null
    training:
      dataset:
        # _target_: torch.utils.data.dataset.ConcatDataset
        datasets:
          # _target_: lidra.config.utils.make_list_from_kwargs
          variantF_v1:
            preprocessor: ${tdfy.preprocessor}
          variantF_v1_complement: 
            preprocessor: ${tdfy.preprocessor}

tdfy:
  reverse_fn:
    strict: false
    checkpoint_path: /checkpoint/3dfy/weiyaowang/lidra/logs/tagged/_submit/fm-force_zeros_cond-trellis500k-rPad.2_colorAug-16x8/lightning/version_0/checkpoints/last.ckpt
    model:
      force_zeros_cond: True