# @package _global_
defaults:
  - ../fm-trellis-trellis500k-tricks-mot-shape-6drotation-normalized-inhouse-vae

  # load pretrained backbone
  - /data/dataset/tdfy/trellis500k/preprocessor@tdfy.preprocessor: train_keep_bg

  - /model/backbone@tdfy.reverse_fn_pretrained: trellis_dit/mot_image_large_shape_6drotation_normalized_pretrained
  - override /model/backbone/dit/embedder@tdfy.reverse_fn_pretrained.model.condition_embedder: image_dino_mask_embedder_fuser
  - override /data/dataset/tdfy/trellis500k@loop.dataloaders.training.dataset: training_fo_v4

module:
  # cropped image, cropped mask, full image, mask
  batch_conditions_mapping: 
    image: image
    mask: mask
    rgb_image: rgb_image
    rgb_image_mask: rgb_image_mask
  generator:
    backbone:
      reverse_fn:
        unconditional_handling: "add_flag"

lr: 1e-4  # Smaller learning rate; tune yourself

loop:
  max_epochs: 100
  dataloaders:
    validation: null
    # training:
    #   dataset:
    #     datasets:
    #       variantF_v4:
    #         preprocessor: ${tdfy.preprocessor}
    #         latent_dir: ${tdfy.latent_dir}

tdfy:
  reverse_fn_pretrained:
    checkpoint_path: /fsx-3dfy-v2/haotang/3dfy/lidra/logs/tagged/_submit/v0-pretrain-tricks-shape-6drotation-normalized-training-v6/lightning/version_0/checkpoints/epoch187.ckpt
    strict: false
    device: "cpu"
    remove_name:
      - "_base_models.generator.reverse_fn.backbone.condition_embedder.idx_emb"
    model:
      use_fp16: True
      force_zeros_cond: True
  reverse_fn: ${tdfy.reverse_fn_pretrained}

batch_size: 4