# @package _global_
defaults:
  ## base setup
  - /run/train: base

  ## loop setup
  - /loop: mock

  # dataset setup
  - /data/module@loop.dataloaders: ???

  - _self_

batch_size: 1
validation_batch_size: ${batch_size}
lr: 1e-4

loop:
  dataloaders:
    training:
      batch_size: ${batch_size}
      collate_fn: ${tdfy.collator}

    validation:
      batch_size: ${validation_batch_size}
      collate_fn: ${tdfy.collator}

tdfy:
  collator: ???
module: ???
