_target_: lidra.metrics.analysis.definitions.Report
_convert_: all

tables:
  shape:
    _target_: lidra.metrics.analysis.definitions.Table
    columns:
      - f1
      - precision
      - recall
      - chamfer_distance
    best_of_trials:
      _target_: lidra.metrics.analysis.definitions.BestOfNSelection
      select_column: chamfer_distance
      select_max: false

  oriented:
    _target_: lidra.metrics.analysis.definitions.Table
    columns:
      - oriented_f1
      - oriented_precision
      - oriented_recall
      - oriented_chamfer_distance
      - oriented_rot_error_deg
    best_of_trials:
      _target_: lidra.metrics.analysis.definitions.BestOfNSelection
      select_column: oriented_chamfer_distance
      select_max: false
    thresholds:
      oriented_rot_error_deg:
        _target_: lidra.metrics.analysis.definitions.Threshold
        thresholds: [5, 15, 30]
        higher_is_better: false

  scale:
    _target_: lidra.metrics.analysis.definitions.Table
    columns:
      - scale_abs_rel_error
      - scale_abs_log_rel_err
      - scale_abs_rel_delta1_acc
      - scale_abs_rel_delta2_acc
      - scale_abs_rel_delta3_acc
    best_of_trials:
      _target_: lidra.metrics.analysis.definitions.BestOfNSelection
      select_column: scale_abs_rel_error
      select_max: false
    thresholds:
      scale_abs_rel_error:
        _target_: lidra.metrics.analysis.definitions.Threshold
        thresholds: [0.05, 0.10, 0.20]  # 5%, 10%, 20% relative error
        higher_is_better: false
      scale_abs_log_rel_err:
        _target_: lidra.metrics.analysis.definitions.Threshold
        thresholds: [0.05, 0.10, 0.20]  # log scale thresholds
        higher_is_better: false

  translation:
    _target_: lidra.metrics.analysis.definitions.Table
    columns:
      - trans_err
      - trans_abs_rel_error
      - trans_abs_log_rel_err
      - trans_angle_err_deg
      - trans_cos_angle
    best_of_trials:
      _target_: lidra.metrics.analysis.definitions.BestOfNSelection
      select_column: trans_abs_rel_error
      select_max: false
    thresholds:
      trans_err:
        _target_: lidra.metrics.analysis.definitions.Threshold
        thresholds: [0.05, 0.10, 0.25]  # absolute error thresholds
        higher_is_better: false
      trans_angle_err_deg:
        _target_: lidra.metrics.analysis.definitions.Threshold
        thresholds: [0.5, 1.25, 5.0]  # degrees
        higher_is_better: false

  translation_normalized:
    _target_: lidra.metrics.analysis.definitions.Table
    columns:
      - trans_norm_err
      - trans_norm_abs_rel_error
      - trans_norm_abs_log_rel_err
      - trans_norm_abs_rel_delta1_acc
      - trans_norm_abs_rel_delta2_acc
      - trans_norm_abs_rel_delta3_acc
    best_of_trials:
      _target_: lidra.metrics.analysis.definitions.BestOfNSelection
      select_column: trans_norm_abs_rel_error
      select_max: false
    thresholds:
      trans_norm_err:
        _target_: lidra.metrics.analysis.definitions.Threshold
        thresholds: [0.05, 0.10, 0.25]  # normalized error thresholds
        higher_is_better: false