"""Stable IDs for RF-DETR inference-path implementations."""

from inference_models.models.optimization.ids import BASE_IMPLEMENTATION_ID

RFDETR_PREPROCESSOR_BASE = BASE_IMPLEMENTATION_ID
RFDETR_PREPROCESSOR_THREADED_EXACT_V1 = "threaded-exact-v1"
RFDETR_PREPROCESSOR_TRITON_UNIVERSAL_V1 = "triton-universal-v1"
RFDETR_PREPROCESSOR_ENV_NAME = "INFERENCE_MODELS_RFDETR_PREPROCESSOR"
RFDETR_PREPROCESSOR_MAX_WORKERS_ENV_NAME = (
    "INFERENCE_MODELS_RFDETR_PREPROCESSOR_MAX_WORKERS"
)
RFDETR_PREPROCESSOR_DEFAULT_MAX_WORKERS = 4
RFDETR_POSTPROCESSOR_BASE = BASE_IMPLEMENTATION_ID
RFDETR_POSTPROCESSOR_TRITON_FUSED_V1 = "triton-fused-v1"
RFDETR_POSTPROCESSOR_ENV_NAME = "INFERENCE_MODELS_RFDETR_POSTPROCESSOR"
