_target_: lidra.model.backbone.trellis.models.structured_latent_vae.encoder.SLatEncoderTdfyWrapper
"resolution": 64
"in_channels": 1024
"model_channels": 768
"latent_channels": 8
"num_blocks": 12
"num_heads": 12
"mlp_ratio": 4
"attn_mode": swin
"window_size": 8
"use_fp16": true
pretrained_ckpt_path: ${cluster.path.weights}/tdfy/TRELLIS-image-large/ckpts/slat_enc_swin8_B_64l8_fp16.safetensors
