_target_: lidra.model.backbone.trellis.models.sparse_structure_vae.SparseStructureEncoderTdfyWrapper
in_channels: 1
latent_channels: 8
num_res_blocks: 2
num_res_blocks_middle: 2
channels: [32, 128, 512]
use_fp16: true
pretrained_ckpt_path: /fsx-3dfy-v2/shared/weights/tdfy/TRELLIS-image-large/ckpts/ss_enc_conv3d_16l8_fp16.safetensors
# reshape_input_to_cube: false