_target_: lidra.model.backbone.generator.ddim.model.DDIM
reverse_fn: ???
solver:
  _target_: lidra.model.backbone.generator.ddpm.solver.Velocity
training_schedule:
  _target_: lidra.model.backbone.generator.ddpm.schedule.Schedule
  max_t: 1000
  schedule_fn:
    _target_: lidra.model.backbone.generator.ddpm.schedule.linear
    beta_1: 1e-4
    beta_T: 0.02
    T: ${..max_t}
generative_schedule:
  _target_: lidra.model.backbone.generator.ddpm.schedule.LinearSubSchedule
  max_t: 10
  schedule: ${..training_schedule}
