_target_: lidra.model.backbone.generator.ddpm.model.DDPM
reverse_fn: ???
schedule:
  _target_: lidra.model.backbone.generator.ddpm.schedule.Schedule
  max_t: 1000
  schedule_fn:
    _target_: lidra.model.backbone.generator.ddpm.schedule.linear
    beta_1: 1e-4
    beta_T: 0.02
    T: ${..max_t}
