_target_: lidra.model.backbone.generator.flow_matching.model.FlowMatching
reverse_fn:
  _target_: lidra.model.backbone.generator.classifier_free_guidance.ClassifierFreeGuidance
  backbone: ???
  p_unconditional: 0.1
  strength: 3.0
  unconditional_handling: "zeros"
sigma_min: 0.
inference_steps: 50
time_scale: 1000.