_target_: lidra.model.backbone.dit.embedder.image_and_masks.Imagex2AndMaskx2
image_embedder:
    _target_: lidra.model.backbone.dit.embedder.dino.Dino
    dino_model: dinov2_vitl14_reg
    input_size: 518
mask_embedder:
    _target_: lidra.model.backbone.dit.embedder.dino.DinoForMasks
    backbone: ${..image_embedder}
