_target_: lidra.model.backbone.dit.embedder.embedder_fuser.EmbedderFuser
embedder_list:
  - - _target_: lidra.model.backbone.dit.embedder.dino.Dino
      dino_model: "dinov2_vitl14_reg"
      input_size: 518
      normalize_images: True
    - - ["image", "dino_masked_image"]
  - - _target_: lidra.model.backbone.dit.embedder.moge.MoGe
    - - ["image", "moge_masked_image"]
  - - _target_: lidra.model.backbone.dit.embedder.siglip2.SigLIP2
      patch_token: True
    - - ["image", "siglip2_masked_image"]
use_pos_embedding: learned
projection_net_hidden_dim_multiplier: 4.0