_target_: lidra.model.backbone.dit.embedder.embedder_fuser.EmbedderFuser
embedder_list:
  - - _target_: lidra.model.backbone.dit.embedder.dino.Dino
      repo_or_dir: /fsx-3dfy-v2/shared/weights/dinov3
      source: local
      dino_model: "dinov3_vitl16"
      input_size: 512
      normalize_images: True
      backbone_kwargs:
        weights: /fsx-3dfy-v2/shared/weights/dinov3_vitl16_pretrain_lvd1689m-8aa4cbdd.pth
    - - ["image", "dino_masked_image"]
use_pos_embedding: learned
projection_net_hidden_dim_multiplier: 4.0
