_target_: lidra.model.backbone.dit.embedder.embedder_fuser.EmbedderFuser
use_pos_embedding: learned
projection_net_hidden_dim_multiplier: 4.0
embedder_list:
  - - _target_: lidra.model.backbone.dit.embedder.dino.Dino
      dino_model: "dinov2_vitl14_reg"
      input_size: 518
      normalize_images: True
    - - ["image", "cropped"]
      - ["rgb_image", "full"]
  - - _target_: lidra.model.backbone.dit.embedder.dino.Dino
      dino_model: "dinov2_vitl14_reg"
      input_size: 518
      normalize_images: True
    - - ["mask", "cropped"]
      - ["rgb_image_mask", "full"]