_target_: lidra.model.backbone.dit.embedder.embedder_fuser.EmbedderFuser
use_pos_embedding: learned
projection_net_hidden_dim_multiplier: 4.0
embedder_list:
  - - _target_: lidra.model.backbone.dit.embedder.dino.Dino
      dino_model: "dinov2_vitl14_reg"
      input_size: 518
      normalize_images: True
    - - ["image", "cropped"]
      - ["rgb_image", "full"]
  - - _target_: lidra.model.backbone.dit.embedder.dino.Dino
      dino_model: "dinov2_vitl14_reg"
      input_size: 518
      normalize_images: True
    - - ["mask", "cropped"]
      - ["rgb_image_mask", "full"]
  - - _target_: lidra.model.backbone.dit.embedder.pointmap.PointPatchEmbed
      remap_output: linear
      input_size: 256
      patch_size: 8
      embed_dim: 512
    - - ["pointmap", "cropped"]
      - ["rgb_pointmap", "full"]

drop_modalities_weight:
  - - ["pointmap", "rgb_pointmap"]
    - 1.0
dropout_prob: ${tdfy.pointmap_embedder.dropout_prob}
force_drop_modalities: ${tdfy.pointmap_embedder.force_drop_modalities}