import os

HTTP_CODES_TO_RETRY = {408, 429, 502, 503, 504}
REQUEST_TIMEOUT = 5
MAX_SHARD_SIZE = 256
MAX_SHARDS_UPLOAD_PROCESSES = int(os.getenv("MAX_SHARDS_UPLOAD_PROCESSES", "8"))
MIN_IMAGES_TO_FORM_SHARD = 32
SUGGESTED_MAX_VIDEOS_IN_BATCH = 1000
MAX_DOWNLOAD_THREADS = int(os.getenv("MAX_DOWNLOAD_THREADS", "8"))
