# @package _global_
defaults:
  - /run@_here_: base # Allows tagging
  - /hydra: local
  - /compute: 1x1
  - /data/dataset/visualization@dataset: multi_object_r3
  - /cluster: aws-h100
  - _self_

# Name of the demo inference config (without .yaml), e.g., demo_h100_3dfy_v3
# This is passed through to visualize_results as-is.
demo_version: demo_h100_3dfy_v3

# Dataset object to instantiate via hydra.utils.instantiate
# Defaults to the visualization/multi_object_r3 dataset config.
# Override at launch with another dataset name from etc/lidra/data/dataset/visualization,
# e.g., `dataset=marketplace`, or override fields directly like
# `dataset.dataset_path=/path/to/data`.

visualization:
  output_dir: ./visualization
  viz_single_obj: false
  export_obj_gif: false
  viz_pm: true
  stage2_only: false

# If a tag name is provided, set the Hydra job name to it for easier monitoring
hydra:
  job:
    name: ${rv.if_not_none:${tag.name},${tag.name},default_hydra_job_name}

cluster:
  slurm:
    timeout: 1440 # 24 hours
