# @package _global_
defaults:
  - base

  # Generator: 
  - /model/backbone@tdfy.reverse_fn: trellis_dit/mm_image_large
  - override /model/backbone/dit/embedder@tdfy.reverse_fn.condition_embedder: image_mask_dino_dino
  - override /model/backbone/generator@module.generator.backbone: flow_matching_cfg

  # Dataset:
  - override /data/module@loop.dataloaders: tdfy/kubric-anything

  - _self_

batch_size: 6


module:
  # batch_conditions_mapping: ["image", "mask"]
  generator:
    backbone:
      reverse_fn:
        backbone: ${tdfy.reverse_fn}


loop:
  max_epochs: 200
  check_val_every_n_epoch: 25
  deterministic: false
  precision: bf16-mixed
  # dataloaders:
  #   validation: null
  callbacks:
    model_checkpoint2:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_on_train_epoch_end: true
      every_n_epochs: 25
      save_top_k: -1

tdfy:
  collator:
    _target_: lidra.data.collator.auto_collate
  reverse_fn:
    resolution: 16
    patch_size: 1
    include_pose: true
    pose_weight: 0.01
    use_checkpoint: false
    model_channels: 1024
