# @package _global_
defaults:
  - base

  # generator
  - /model/backbone@tdfy.reverse_fn: trellis_dit/pretrained_base
  - /model/backbone@tdfy.reverse_fn.model: trellis_dit/mm_image_large
  - override /model/backbone/dit/embedder@tdfy.reverse_fn.model.condition_embedder: imagex2_maskx2_dino_dino

  - override /model/module/tdfy@module: generative-featuresAndPoseToken
  - override /model/backbone/generator@module.generator.backbone: flow_matching_cfg

  # dataset
  - override /data/module@loop.dataloaders: tdfy/kubric-anything

  - _self_


loop:
  max_epochs: 100
  check_val_every_n_epoch: 25
  deterministic: false
  precision: bf16-mixed
  dataloaders:
    training:
      dataset:
        dataset:
          latent_loader_dataset:
            preprocessor: ${tdfy.train_preprocessor}
    validation:
      dataset:
        dataset:
          latent_loader_dataset:
            preprocessor: ${tdfy.val_preprocessor}
  callbacks:
    model_checkpoint2:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_on_train_epoch_end: true
      every_n_epochs: 50
      save_top_k: -1

tdfy:
  pose_weight: 0.01
  reverse_fn:
    checkpoint_path: /checkpoint/3dfy/haotang/lidra/logs/tagged/_submit/v1-pretraining-shape-quaternion-fo-only-noema/lightning/version_0/checkpoints/epoch=199-step=250400-v1.ckpt
    strict: false