"""Structured stream error codes for RTSPS/auth failures (ENT-1544 C1)."""

from enum import Enum


class StreamErrorCode(str, Enum):
    STREAM_CONNECTION_FAILED = "STREAM_CONNECTION_FAILED"
    STREAM_AUTH_FAILED = "STREAM_AUTH_FAILED"
    STREAM_TLS_CERTIFICATE = "STREAM_TLS_CERTIFICATE"
    STREAM_TLS_HANDSHAKE = "STREAM_TLS_HANDSHAKE"
    STREAM_TIMEOUT = "STREAM_TIMEOUT"
    STREAM_NOT_FOUND = "STREAM_NOT_FOUND"
    STREAM_CODEC_UNSUPPORTED = "STREAM_CODEC_UNSUPPORTED"
