from models.base.classification import ClassificationPrediction, ClassificationModel, MultiLabelClassificationPrediction, MultiLabelClassificationModel
from models.base.depth_estimation import DepthEstimationModel
from models.base.documents_parsing import DocumentParsingModel
from models.base.embeddings import TextImageEmbeddingModel
from models.base.instance_segmentation import InstanceSegmentationModel, InstanceDetections
from models.base.keypoints_detection import KeyPointsDetectionModel, KeyPoints
from models.base.object_detection import ObjectDetectionModel, OpenVocabularyObjectDetectionModel, Detections
