# @package _global_

cluster_path: /large_experiments/3dfy/model_weights
trellis_ckpts_dir: ${cluster_path}/TRELLIS-image-large/ckpts

inference_pipeline:
  _target_: lidra.pipeline.inference_pipeline_layout_mitl_pointmap.InferencePipelineLayoutMITLPointMap
  ss_encoder_config_path: ${trellis_ckpts_dir}/ss_encoder.yaml
  ss_encoder_ckpt_path: ${trellis_ckpts_dir}/ss_enc_conv3d_16l8_fp16.safetensors

  layout_model_config_path: ${cluster_path}/layoutv0-r3v0_2-eitr-ptmap-cfg/config_converted.yaml
  layout_model_ckpt_path: ${cluster_path}/layoutv0-r3v0_2-eitr-ptmap-cfg/lightning/version_0/checkpoints/last_converted.ckpt

  depth_model:
    _target_: lidra.pipeline.depth_models.moge.MoGe
    model:
      _target_: moge.model.v1.MoGeModel.from_pretrained
      pretrained_model_name_or_path: Ruicheng/moge-vitl

  dtype: float16
  version: 3dfy_mitl_layout_v4_pm

  layout_condition_input_mapping: []  
  layout_preprocessor:
    _target_: lidra.data.dataset.tdfy.trellis.dataset.PreProcessor
    img_mask_joint_transform: []
    img_mask_pointmap_joint_transform: 
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_and_mask_transforms.crop_around_mask_with_padding
        box_size_factor: 1.2
        padding_factor: 0.0
    img_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        size: 518
    mask_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        interpolation: 0
        size: 518
    pointmap_transform:
      _target_: torchvision.transforms.Compose
      transforms:
      - _partial_: true
        _target_: lidra.data.dataset.tdfy.img_processing.pad_to_square_centered
      - _target_: torchvision.transforms.Resize
        interpolation: 0
        size: 518

  pose_decoder_name: ScaleShiftInvariant
  layout_post_optimization_method:
    _partial_: true
    _target_: lidra.pipeline.inference_utils.layout_post_optimization
    Enable_shape_ICP: true
    Enable_rendering_optimization: true