# @package _global_

cluster_path: /large_experiments/3dfy/model_weights
trellis_ckpts_dir: ${cluster_path}/TRELLIS-image-large/ckpts

inference_pipeline:
  _target_: lidra.pipeline.inference_pipeline_stage2_only.InferenceStage2OnlyPipeline
  slat_decoder_gs_config_path: ${trellis_ckpts_dir}/slat_decoder_gs.yaml
  slat_decoder_gs_ckpt_path: ${trellis_ckpts_dir}/slat_dec_gs_swin8_B_64l8gs32_fp16.safetensors
  slat_decoder_mesh_config_path: ${trellis_ckpts_dir}/slat_decoder_mesh.yaml
  slat_decoder_mesh_ckpt_path: ${trellis_ckpts_dir}/slat_dec_mesh_swin8_B_64l8m256c_fp16.safetensors
  
  use_pretrained_slat: false
  slat_generator_config_path: ${cluster_path}/fm-trellis-features-foFix-ft-8x8/config_converted.yaml
  slat_generator_ckpt_path: ${cluster_path}/fm-trellis-features-foFix-ft-8x8/lightning/version_0/checkpoints/last_converted.ckpt

  dtype: float16
  version: 3dfy_mitl_s2Repro
  decode_formats: ["gaussian", "mesh"]