# @package _global_

cluster_path: /checkpoint/3dfy/
trellis_ckpts_dir: /checkpoint/3dfy/shared/weights/tdfy/TRELLIS-image-large/ckpts
config_dir: ${cluster_path}/haotang/dev/lidra/etc/lidra/

cluster:
  path:
    weights: /checkpoint/3dfy/shared/weights/

inference_pipeline:
  _target_: lidra.pipeline.inference_pipeline_stage2_only.InferenceStage2OnlyPipeline
  slat_decoder_gs_config_path: ${config_dir}/model/backbone/trellis_vae/slat_decoder_gs.yaml
  slat_decoder_gs_ckpt_path: ${trellis_ckpts_dir}/slat_dec_gs_swin8_B_64l8gs32_fp16.safetensors
  slat_decoder_mesh_config_path: ${config_dir}/model/backbone/trellis_vae/slat_decoder_mesh.yaml
  slat_decoder_mesh_ckpt_path: ${trellis_ckpts_dir}/slat_dec_mesh_swin8_B_64l8m256c_fp16.safetensors
  
  use_pretrained_slat: false
  slat_generator_config_path: /checkpoint/3dfy/weiyaowang/lidra/a100_models/fm-features-trellis500k-tricksNoEMA-16x8/config.yaml
  slat_generator_ckpt_path: /checkpoint/3dfy/weiyaowang/lidra/a100_models/fm-features-trellis500k-tricksNoEMA-16x8/last.ckpt

  dtype: float16
  version: 3dfy_mitl_s2Repro
  decode_formats: ["gaussian", "mesh"]