
name: ???

path:
  base: ???
  cache: ${cluster.path.base}/cache
  logs: ${cluster.path.base}/logs
  models: ${cluster.path.base}/models
  datasets: ${cluster.path.base}/datasets
  cwd: ${hydra:runtime.cwd} # https://hydra.cc/docs/configure_hydra/intro/#hydraruntime

slurm:
  constraint: ???
  partition: ???
  qos: ???
  timeout: ??? # in minutes
  mem_per_gpu: 128G
