name: Benchmark Jetson 7.2.0 FlashAttention Parallel Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flash-attn-8way:
    name: Build FlashAttention (8-way)
    runs-on:
      labels: depot-ubuntu-24.04-4
      group: public-depot
    timeout-minutes: 1440
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Build experimental FlashAttention stage
        uses: depot/bake-action@v1
        with:
          files: ./docker/docker-bake.jetson.7.2.0.hcl
          targets: jetson-wheels-flash-attn-8way-jp72
          project: v1xzfwkc4b
