name: Build and Push CPU Container

on:
  release:
    types: [created]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_push:
        type: boolean
        description: "Do you want to push image after build?"
        default: false

env:
  VERSION: '0.0.0' # Default version, will be overwritten

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
      - uses: Read version from file
        run: echo "VERSION=$(DISABLE_VERSION_CHECK=true python ./inference/core/version.py)" >> $GITHUB_ENV
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Build and Push
        uses: depot/build-push-action@v1
        with:
          push: ${{ github.event_name == 'release' || (github.event.inputs.force_push == 'true')}}
          tags: roboflow/roboflow-inference-server-cpu:latest,roboflow/roboflow-inference-server-cpu:${{env.VERSION}}
          cache-from: type=registry,ref=roboflow/roboflow-inference-server-cpu:cache
          cache-to: type=registry,ref=roboflow/roboflow-inference-server-cpu:cache,mode=max
          platforms: linux/amd64,linux/arm64
          file: ./docker/dockerfiles/Dockerfile.onnx.cpu
