name: Test package install - inference-gpu[extras]

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call_is_mergeable:
    uses: ./.github/workflows/check_if_branch_is_mergeable.yml
    secrets: inherit
  build:
    needs: call_is_mergeable
    if: ${{ github.event_name != 'pull_request' || needs.call_is_mergeable.outputs.mergeable_state != 'not_clean' }}
    runs-on: Roboflow-GPU-VM-Runner
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
      - name: 🐍 Set up Python 3.10 to create wheels
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: 🚧 Install GDAL OS library
        run: sudo apt-get update && sudo apt-get install -y libgdal-dev
      - name: 🛞 Create Wheels
        run: |
          make create_wheels
      - name: 🐍 Set up Python ${{ matrix.python-version }} to test package install process
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: 📦 Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements/**') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - name: 🔧 Install CUDA development toolkit
        if: ${{ (github.event.inputs.extras == '' || github.event.inputs.extras == matrix.extras.marker) && (github.event.inputs.python_version == '' || github.event.inputs.python_version == matrix.python-version) }}
        run: |
          mkdir -p ~/apt-cache

          sudo mkdir -p /var/cache/apt/archives
          sudo cp -r ~/apt-cache/* /var/cache/apt/archives/ 2>/dev/null || true

          sudo apt-get update
          sudo apt-get install -y \
              cuda-cudart-dev-12-5 \
              cuda-nvcc-12-5 \
              cuda-profiler-api-12-5 \
              libcurand-dev-12-5 \
              libvips-dev

          sudo cp /var/cache/apt/archives/*.deb ~/apt-cache/ 2>/dev/null || true
          sudo chown -R $(whoami):$(whoami) ~/apt-cache
      - name: 📦 Installing `inference` package...
        run: |
          export CUDA_HOME=/usr/local/cuda-12.5
          export PATH=/usr/local/cuda-12.5/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda-12.5/targets/x86_64-linux/lib64:$LD_LIBRARY_PATH
          export CPATH=/usr/local/cuda-12.5/targets/x86_64-linux/include:$CPATH
          export LIBRARY_PATH=/usr/local/cuda-12.5/targets/x86_64-linux/lib64:$LIBRARY_PATH
          wheel_name=`ls ./dist/inference_gpu-*-py3-none-any.whl | head -n 1`
          pip install "${wheel_name}[clip,gaze,grounding-dino,sam,waf,yolo-world,http,hosted,transformers]"
      - name: 🧪 Testing package installation
        working-directory: "/"
        run: |
          python -c "import os; import platform; print(f'Python version: {platform.python_version()}'); print(f'CWD: {os.getcwd()}'); from inference import get_model"
          python -c "from inference.models.clip import Clip"
          python -c "from inference.models.gaze import Gaze"
          python -c "from inference.models.sam import SegmentAnything"
          python -c "from inference.models.grounding_dino import GroundingDINO"
          python -c "from inference.models.yolo_world import YOLOWorld"
          python -c "from inference.models.florence2 import Florence2, LoRAFlorence2"
