_target_: lidra.model.backbone.trellis.models.structured_latent_vae.decoder_mesh.SLatMeshDecoderTdfyWrapper
resolution: 64
model_channels: 768
latent_channels: 8
num_blocks: 12
num_heads: 12
mlp_ratio: 4
attn_mode: swin
window_size: 8
representation_config:
  use_color: true

  
pretrained_ckpt_path: /home/haotang/dev/TRELLIS-image-large/ckpts/slat_dec_mesh_swin8_B_64l8m256c_fp16.safetensors
use_fp16: true
